### ISSUE TITLE
Is it correct to use abbreviations in the headings?

### ISSUE THREAD

**Issue by SSParamee** [MicrosoftDocs/microsoft-style-guide#108]
Imagine on a previous page, the full definition for an abbreviation is stated. In that case, is it correct having the abbreviation in the heading itself. 
example: 
Page heading: SSO in the sign-in page vs. Single Sign-On in the sign-in page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598da0f-c10d-05fa-a5c3-6e52bc511c35
* Version Independent ID: 353b7f63-2c35-667b-f898-e55ad21558ce
* Content: [Headings - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/scannable-content/headings)
* Content Source: [styleguide/scannable-content/headings.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/scannable-content/headings.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by chanakavp** [comment]
https://docs.microsoft.com/en-us/style-guide/acronyms#be-careful-with-acronyms-in-titles-and-headings says the following:

**Be careful with acronyms in titles and headings**
Avoid using an acronym for the first time in a title or heading, unless it's a keyword that you need to place in the title or heading for SEO. If the first use of the acronym is in a title or heading, introduce the acronym (in parentheses, following the spelled-out term) in the following body text.

**Comment by ashishguptaiitb** [comment]
Also, every page is an entry point in the search-based content consumption model. So unless it is a sequential doc, say in PDF format, then a definition from the 'previous page' won't help a reader who directly reaches the so-called 'next page'.
