### ISSUE TITLE
Consider changing code samples, constants, and others

### ISSUE THREAD

**Issue by italicize** [MicrosoftDocs/microsoft-style-guide#11]
- Clarify **Code samples**. Delete "including keywords and variables" from the element description, because **Keywords** and **Variables** have their own rows. Maybe change the element description to only **Code samples** and the convention to "Monospace, both within text and as separate paragraphs, including the keywords, variables, and user-defined program elements in the code samples."
- Change **Constants** to **Constants and enumerations**.
- Add a row for **Objects** with "Bold. Capitalization varies." as the convention and **Application** and **Selection** as the examples.
- Change **Parameters** to **Arguments and parameters** and move the row to the top. Add "Named arguments can be italic and bold." to the conventions. Add _object_.**Add _item, key, before, after_** to the examples.
- Add **Set** to the examples for **Statements**, or another example that isn't all caps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548ee875-6179-9f2d-7e1d-6af87a7d3a2f
* Version Independent ID: f6df8d87-ab99-c35e-9d67-29ca979c10f5
* Content: [Formatting developer text elements - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/developer-content/formatting-developer-text-elements)
* Content Source: [styleguide/developer-content/formatting-developer-text-elements.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/developer-content/formatting-developer-text-elements.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Thanks, these are great suggestions! We're in the process of revising this topic, so I'll add your comments to the other revisions being considered.
