### ISSUE TITLE
UI text example

### ISSUE THREAD

**Issue by jcollinsdim** [MicrosoftDocs/microsoft-style-guide#12]
This doesn't look right for the "UI text" example: "Hmm … looks like that’s a broken link." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28c9871-f3a6-2dc1-1494-93f981f50238
* Version Independent ID: 8e95f7bc-399a-7648-36bd-8dd7dc90f347
* Content: [Formatting common text elements - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/text-formatting/formatting-common-text-elements)
* Content Source: [styleguide/text-formatting/formatting-common-text-elements.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/text-formatting/formatting-common-text-elements.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
What about it seems wrong? "UI text" can refer to a number of things, including button labels, error messages, notifications, steps in a wizard, and so on. What would you expect to see here instead? Thanks!

**Comment by jcollinsdim** [comment]
Perhaps more examples than that one as in developer text and instructions:
https://docs.microsoft.com/en-us/style-guide/developer-content/formatting-developer-text-elements
https://docs.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions

Otherwise, instead of looking like an example, it just looks like someone meant there to be a link.

**Comment by jcollinsdim** [comment]
You closed this without making any changes or replying to my comment?

**Comment by camind** [comment]
Oh, my mistake. I was thinking of a different thread. Thanks for the additional info. This is on the list of revisions to be made.

**Comment by jcollinsdim** [comment]
Thanks!
