### ISSUE TITLE
A useful additional case for the en dash

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/microsoft-style-guide#143]
I recommend that you open up the en dash for use in one more scenario. It's useful as a **_layout element_** with definitions and descriptions. For example ...

* Link lists (e.g., topics in an *Additional resources* or other section that require a further remark) ...

  * [Topic title 1](#) &ndash; This is a remark or description about the first topic.
  * [Topic title 2](#) &ndash; This is a remark or description about the second topic.

* Definition lists

  * [System.String](#) &ndash; Represents text as a sequence of UTF-16 code units.
  * [String(SByte\*)](#) &ndash; Initializes a new instance of the String class to the value indicated by a pointer to an array of 8-bit signed integers.

In these cases imo, the en dash looks nicer :eyes: than colon-space syntax ...

* Link lists (e.g., topics in an *Additional resources* or other section) ...

  * [Topic title 1](#): This is a remark or description about the first item.
  * [Topic title 2](#): This is a remark or description about the second item.

* Definition lists

  * [System.String](#): Represents text as a sequence of UTF-16 code units.
  * [String(SByte\*)](#): Initializes a new instance of the String class to the value indicated by a pointer to an array of 8-bit signed integers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88ebe26-c748-e668-4b55-42b87fd9c86e
* Version Independent ID: da313f5c-fec4-990d-0ae2-185ff6a894e7
* Content: [En dashes - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/enes)
* Content Source: [styleguide/punctuation/dashes-hyphens/enes.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/dashes-hyphens/enes.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by ashishguptaiitb** [comment]
🤔 IMHO, formatting that looks nice may or may not be the correct method to adopt.
For what it is worth, see that definition list is defined without a colon or a dash at w3.org

See https://www.w3.org/MarkUp/html3/deflists.html
Try the formatting yourself: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_dl_default_css

**Comment by guardrex** [comment]
Yes, but that breaks the text to a different line, which I almost never see in practice.

It's the standard for Microsoft's official documents. I'm requesting the addition so that it can be used in MS's docs.

**Comment by ashishguptaiitb** [comment]
Yes @guardrex, that it does. And no issues with the proposal. I was just sharing my perspective on the formatting of a definition list.

**Comment by guardrex** [comment]
I'm going to take this to a different repo to get more mgmt 👀 on it. I'll re-open this if we get a good outcome.
