### ISSUE TITLE
Superfluous section heading

### ISSUE THREAD

**Issue by jedippold** [MicrosoftDocs/microsoft-style-guide#148]
It took me a minute to understand in what context we were being told to "use sentence-style capitalization." I saw another heading in the nav pane for formatting titles, so what were we formatting here? Oh, we should use sentence-style capitalization for sentences. I'm not sure this is worth saying, let alone in its own heading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf46744-5cbc-a35e-e9e4-c43ada32ef2a
* Version Independent ID: 9c1d12dd-20a9-9af7-e7c8-44df1430ac63
* Content: [Use sentence-style capitalization - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/use-sentence-style-capitalization)
* Content Source: [styleguide/text-formatting/using-type/use-sentence-style-capitalization.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/text-formatting/using-type/use-sentence-style-capitalization.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by ashishguptaiitb** [comment]
See #149  for more context.

**Comment by jedippold** [comment]
To be clear, in this issue I was suggesting removing the "Use sentence-style capitalization" heading because it seems tautological to suggest sentence style for sentences. The suggestion to avoid all uppercase letters might be useful, but that's covered in the A-Z section (https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/u/uppercase). 

The point of #149 was to suggest removing the "Using type" heading and putting its child topics under "Text formatting."

**Comment by ashishguptaiitb** [comment]
Yes @jedippold. Agree with the suggestion. Stating this in title and then in the first paragraph is redundant. It is obvious.
I was just interlinking this with more context about updating its parent article that you kindly provided in #149. When a writer fixes this issue, I hope they address both issues in one go :)
