### ISSUE TITLE
Combine into Text formatting heading?

### ISSUE THREAD

**Issue by jedippold** [MicrosoftDocs/microsoft-style-guide#149]
The heading "Using type" and the intro sentence about the "cornerstone of modern design" suggest some kind of thoughtful treatment of typography, but all the section elements tell you is to use title caps, left align, and don't compress line spacing. These are not sufficient for beautiful design. Can these rudimentary rules for text formatting be included in the "Text formatting" section instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178ab02-2711-5c7e-25b3-606c33947f86
* Version Independent ID: b41ccea6-33a7-8bec-d44d-1477122d7f8c
* Content: [Using type - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/)
* Content Source: [styleguide/text-formatting/using-type/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/text-formatting/using-type/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by ashishguptaiitb** [comment]
👍 to merge 3 different small articles into a single parent. 

Parent = https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/
Three nested articles to be merged into parents are:
* https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/use-sentence-style-capitalization
* https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/use-left-alignment
* https://docs.microsoft.com/en-us/style-guide/text-formatting/using-type/dont-compress-line-spacing

The benefit of such content merging:
* Do away with confusing page titles.
* Reduce fragmentation of related content over 3 pages.

**Comment by jedippold** [comment]
To clarify, I was suggesting these small articles be moved under the parent heading "Text formatting" and removing "Using type," since that heading has so little content, and doesn't deliver on the  promises made in the intro text.  I hadn't thought of merging the subtopics, but that could be done.
