### ISSUE TITLE
Create list of biased terms to avoid

### ISSUE THREAD

**Issue by beatrizz** [MicrosoftDocs/microsoft-style-guide#163]
It'd be useful to have a list of biased terms we should avoid in a format that software projects can parse to look for these words automatically (e.g. a text file with a word per line or CSV).

Is there something like that? It could be a file in this repo.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3fbd78-e2ad-bfc6-9f2f-13f739b57937
* Version Independent ID: 9ce3e837-12b6-e7b8-6bef-597ec2570dbb
* Content: [Bias-free communication - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/bias-free-communication#feedback)
* Content Source: [styleguide/bias-free-communication.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/bias-free-communication.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by ashishguptaiitb** [comment]
I understand where you are coming from. I have the same need. However, even if someone or some organization provides a list, it'll never a definitive master list. In that sense, having an editor and being cognizant helps more. 

From the perspective of making a start somewhere and doing a quick audit, we all need some list (any list!) to start with. You may want to quickly assemble a list of words from these sources:

* MS style guide examples and articles
* Google's list shared at https://developers.google.com/style/word-list
* Accessibility-related appropriate usage shared at: 
  * https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms
  * https://about.muse.jhu.edu/media/uploads/muse_accessibility_style_guide.pdf
  * https://www.section508.gov/manage/laws-and-policies/quick-reference-guide
* Lists of so-called 'politically-correct' words, which I'd rather call equitable words or simply call it appropriate writing. These need to be crowd-sourced all the way from common sense to the Internet :) A quick web search shows me this URL at the top: https://bnp.org.uk/politically-correct-words/. Some such top search results will give us quite a good list to avoid and audit for.

I hope this helps you get started. I look forward to the amazing MS Style Guide sharing some such lists as you asked for :)

**Comment by beatrizz** [comment]
Thanks @ashishguptaiitb ! I agree. If the list was in a public repo, we could open PRs to edit it (that could go through whichever review process seems appropriate).

@mmduyzend has also pointed me to the [PoliCheck](https://policheck.azurewebsites.net/) tool and the [PoliCheck build task](https://www.1eswiki.com/wiki/PoliCheck_Build_Task), which I haven't had time to look into yet but could be what we're looking for.

**Comment by ashishguptaiitb** [comment]
Cool. Happy to help @beatrizz . Thanks for sharing PoliCheck tool.
