### ISSUE TITLE
Table at the bottom of this page looks broken in a web browser

### ISSUE THREAD

**Issue by pivic** [MicrosoftDocs/microsoft-style-guide#166]
The table that is at the end of this page looks broken when viewing it on GitHub.

However, when viewing it in VSCode, it looks pristine.

What gives? I guess GitHub has some kind of Markdown incompatibility... Anyway, the table should be corrected so that https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens doesn't look bad in a web browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
* Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
* Content: [Hyphens - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)
* Content Source: [styleguide/punctuation/dashes-hyphens/hyphens.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/dashes-hyphens/hyphens.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by mbellthomson** [comment]
Hello, Thank you for bringing this to our attention. We will look into this and correct it when possible. Thanks again, Melissa

**Comment by ashishguptaiitb** [comment]
@mbellthomson I see that the request is closed without a fix/content update. Are you tracking it elsewhere to ensure it is fixed when its time comes or is this considered not worth tracking with an open issue?

**Comment by mbellthomson** [comment]
@ashishguptaiitb Yes, we are tracking this. Thank you.

**Comment by pivic** [comment]
@mbellthomson Is there a way to not only log bugs but feature requests - i.e. suggestions to have things included - as well? I mean, for Microsoft Writing Style Guide.
