### ISSUE TITLE
Advertise license as CC-By

### ISSUE THREAD

**Issue by camerons** [MicrosoftDocs/microsoft-style-guide#171]
On your webpage you advertise your license as "© 2020 Microsoft. All rights reserved."

However, from your github style guide home page https://github.com/MicrosoftDocs/microsoft-style-guide, you point to a CC-By license: https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/LICENSE

I suggest aligning these two statements of license so that they are not ambiguous.

Cheers, Cameron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by mbellthomson** [comment]
Hello Cameron, 
I am the Editor to the Microsoft Writing Style Guide. Thank you for providing feedback on this. 

Could you kindly clarifying which portion of the license information you find to be ambiguous? Are you referring to the "All rights reserved" text on the Microsoft Writing Style Guide Welcome page?

Thanks,
Melissa

**Comment by camerons** [comment]
Hi Melissa, nice to meet you, and thanks for your response.

There are a few reasons for my feedback:

* Yes, "all rights reserved" implies to me as a reader that I am not allowed to reproduce this material. It feels confronting and unfriendly to a reader, which I suspect is not the intent of this guide.
* My non-legal understanding is that such a statement is not required, as implied by https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence
* A warmer, more welcoming statement, which hopefully will attract more positive feedback would be to include a CC-By statement  and logo where you currently have the "All rights reserved".

Further:

* I'm one of the coordinators behind [The Good Docs Project](https://thegooddocsproject.dev) where we aim to tackle many of the challenges tech writers face. This comment stems from [patterns and anti-patterns related to style guides](https://docs.google.com/document/d/1Uo3Rcc-rRaN4kmJpqwtUaVRJmDbYI4TkwjuNWNuBu9A/edit#heading=h.ykjfd8gdhiyj). I'd be interested to discuss this further with you and others at Microsoft if you are up for it? Contact: shortcam AT  goo gle DOT com

Warm regards, Cameron Shorter
