### ISSUE TITLE
'Drop-down'

### ISSUE THREAD

**Issue by pivic** [MicrosoftDocs/microsoft-style-guide#172]
There are two things that should be fixed:

* Remove unnecessary space characters.
* Rewrite the [drop-down](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/d/drop-down.md) topic.

Here's my explanation in regard to a needed rewrite:

When it comes to grammar, Microsoft refer to Chicago Style: https://docs.microsoft.com/en-us/style-guide/grammar/grammar-and-parts-of-speech

* Chicago Style would like to change 'drop-down' in Microsoft Writing Style Guide: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0153.html

Why not allow 'dropdown', allow the noun form of the word, and go with Chicago Style/Merriam-Webster? If they won't be allowed, you should remove the parts about adhering to CS/M-W.

**Comment by mbellthomson** [comment]
Thank you for logging this issue. It is being tracked internally.

**Comment by pivic** [comment]
Thanks, @mbellthomson! Will this issue be updated when the internal investigation is concluded?

**Comment by mbellthomson** [comment]
@pivic , Yes- I will keep this issue open until there has been a change in the Microsoft Writing Style Guide. Thanks again for logging it.
