### ISSUE TITLE
Please add allow list and deny list.

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/microsoft-style-guide#173]
Please add Allow List and Deny List.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a09d7650-47d1-1315-9899-0c8c2ede75cb
* Version Independent ID: 7e1c7ede-8eed-c87d-8548-f269a99c3f2a
* Content: [whitelist - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/whitelist)
* Content Source: [styleguide/a-z-word-list-term-collections/w/whitelist.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/w/whitelist.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by mbellthomson** [comment]
Thank you for logging this issue. These terms are currently under review by the Microsoft Editorial Board and guidance on them in the Microsoft Writing Style Guide will be updated in the near future.
