### ISSUE TITLE
Please add allow list.

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/microsoft-style-guide#174]
Per the hackathon, please add deny list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6444ab6d-25d2-415c-f481-485727f527d1
* Version Independent ID: a3cc73d3-c025-9359-1dd2-6c67331fcd0f
* Content: [blacklist - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blacklist)
* Content Source: [styleguide/a-z-word-list-term-collections/b/blacklist.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/b/blacklist.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by mbellthomson** [comment]
Thank you for logging this issue. The Microsoft Editorial Board is currently reviewing this topic and it will be updated in the near future.
