### ISSUE TITLE
Please update page with alternative terms

### ISSUE THREAD

**Issue by adegeo** [MicrosoftDocs/microsoft-style-guide#176]
This page simply says Don't use and doesn't give any actual guidance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f28dc5-a81f-5c62-03ab-0038a174c00a
* Version Independent ID: b9fd6557-1e56-6c38-6d63-e5c662cb1216
* Content: [black box - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/black-box)
* Content Source: [styleguide/a-z-word-list-term-collections/b/black-box.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/b/black-box.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by mbellthomson** [comment]
Hi, My name is Melissa and I'm the Editor for Microsoft's Style Guides, including the Microsoft Writing Style Guide (MWSG). 
Thank you for your feedback on _black box_. This topic will be reviewed to see if it can be improved. In the meantime, if you have questions on terminology that are not covered in the MWSG, please feel free to reference other grammar resources such as the Chicago Manual of Style or the American Heritage Dictionary. 
Thanks again.
