### ISSUE TITLE
Table is not rendered

### ISSUE THREAD

**Issue by chedlid** [MicrosoftDocs/microsoft-style-guide#181]
The table under **Capitalization in hyphenated compound words** is not correctly rendered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
* Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
* Content: [Hyphens - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)
* Content Source: [styleguide/punctuation/dashes-hyphens/hyphens.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/dashes-hyphens/hyphens.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by chanakavp** [comment]
This page renders fine on [GitHub ](styleguide/punctuation/dashes-hyphens/hyphens.md)but not on Microsoft Docs.
