### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by amyguenther** [MicrosoftDocs/microsoft-style-guide#19]
Wonderfully written and very helpful--thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a2bc83-7b1a-f28b-2ba6-4ec3c0d3f18f
* Version Independent ID: c90f4bc6-9865-e5c7-53de-914dd398baaa
* Content: [Microsoft's brand voice : above all, simple and human - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human)
* Content Source: [styleguide/brand-voice-above-all-simple-human.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/brand-voice-above-all-simple-human.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Thanks! We're very glad you find the style guide to be helpful.
