### ISSUE TITLE
mentions.md file is missing 

### ISSUE THREAD

**Issue by rmoyano** [MicrosoftDocs/microsoft-style-guide#212]
Hello, 

I was reading the style guide in [*Puntuaction section*](https://docs.microsoft.com/en-us/style-guide/punctuation/) and found out that [@mentions](https://docs.microsoft.com/en-us/style-guide/punctuation/@mention.md) article link is broken, the file *mention.md* is missing in repository.

**Comment by maitesadaba** [comment]
Hi Rafa,

Thanks for your email. We are indeed having some issues with that link, so we are currently trying to solve this issue.

Thank you!
Maite

From: Rafa Moyano ***@***.***>
Sent: Saturday, March 13, 2021 1:51 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] mentions.md file is missing (#212)


Hello,

I was reading the style guide in Puntuaction section<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fpunctuation%2F&data=04%7C01%7Cv-maites%40microsoft.com%7C7012d38bf8ed428043bf08d8e5ba16b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637511934836042547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ubocec94Cr6xHdm8ShJgJCSPq%2FqQG8JpVwXfHmBZU%2FI%3D&reserved=0> and found out that @mentions<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fpunctuation%2F%40mention.md&data=04%7C01%7Cv-maites%40microsoft.com%7C7012d38bf8ed428043bf08d8e5ba16b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637511934836052503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yPU%2FEE15n9Z%2BTKQDq9j3pIuoca2wVGNL0hzWxxJB2pI%3D&reserved=0> article link is broken, the file mention.md is missing in repository.

-
