### ISSUE TITLE
Wrong italicisation

### ISSUE THREAD

**Issue by UX-Writer-Debbie** [MicrosoftDocs/microsoft-style-guide#213]
[Enter feedback here]
_or_ is wrongly italicized. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b2106b-62f8-d81d-0a96-fe00e79f40fc
* Version Independent ID: bad60c48-04c2-5bec-025a-e366bd99b63c
* Content: [initiate - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/initiate)
* Content Source: [styleguide/a-z-word-list-term-collections/i/initiate.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/i/initiate.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by maitesadaba** [comment]
Hello,
You are completely right. We will modify this in our next update.

Thanks!
Maite

From: UX-Writer-Debbie ***@***.***>
Sent: Monday, March 15, 2021 12:19 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] Wrong italicisation (#213)


[Enter feedback here]
or is wrongly italicized.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 67b2106b-62f8-d81d-0a96-fe00e79f40fc
  *   Version Independent ID: bad60c48-04c2-5bec-025a-e366bd99b63c
  *   Content: initiate - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fa-z-word-list-term-collections%2Fi%2Finitiate&data=04%7C01%7Cv-maites%40microsoft.com%7C89dd93830ea547cd99a808d8e73f7e2d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637513607226733445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wTLEkCMTgslSTMplSvgNadog1Hk2n%2FqtPK85qlQXwYY%3D&reserved=0>
  *   Content Source: styleguide/a-z-word-list-term-collections/i/initiate.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fa-z-word-list-term-collections%2Fi%2Finitiate.md&data=04%7C01%7Cv-maites%40microsoft.com%7C89dd93830ea547cd99a808d8e73f7e2d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637513607226743442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JXH4R%2F43RZ7dK0Qt6WYWf81cyjtdYvgjOa0cttYu3WA%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7C89dd93830ea547cd99a808d8e73f7e2d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637513607226743442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lCiVi1R28uaPOHZSEVMeev1ezLTooC1ekUSOTMv7bjk%3D&reserved=0>
  *   Microsoft Alias: pallep
