### ISSUE TITLE
Unable to understand the message

### ISSUE THREAD

**Issue by rishumehra** [MicrosoftDocs/microsoft-style-guide#22]
This information for 'given' is not at all clear. It's even more confusing. Even examples are also a little misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62af4ea9-6730-aa13-40d0-aadc24b52bc5
* Version Independent ID: 53488e8f-4cd8-4fa6-8895-35cf350bb03f
* Content: [given - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/g/given)
* Content Source: [styleguide/a-z-word-list-term-collections/g/given.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/g/given.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Thanks for your feedback. We'll take a look at this and see if we can clarify the guideline.
