### ISSUE TITLE
Contradiction in using hyphen with prefix **re**

### ISSUE THREAD

**Issue by vremn** [MicrosoftDocs/microsoft-style-guide#226]
Hello!

On the page that I'm now commenting, instructions imply there's only one option to spell **reuse** (without hyphen); as it can only mean use again. 

On the other hand, on [this page](https://support.microsoft.com/en-us/office/find-and-use-the-content-you-need-when-you-need-without-leaving-word-860118fc-1f61-41f6-922f-40084a284658), you interchangeably use *reuse* and *re-use* in the blog. 

Would you please explain a difference, because as a Technical Writer I heavily rely on Microsoft technical writing instructions and rules and need to understand the case. 

Thanks in advance and have good day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3ac5f4-d755-0e7d-623e-9d8eab510309
* Version Independent ID: c52a5c1d-1ed4-d7bc-1d0d-c62a18aff784
* Content: [re- - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/re)
* Content Source: [styleguide/a-z-word-list-term-collections/r/re.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/r/re.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @vremn  and thanks for the feedback. Our guidance is to close compound forms with "re" unless there may be confusion. However, we can't control how people out in the wild use "re" and so you will see inconsistent use of the prefix and hyphen out there. You are correct that "reuse" should always be spelled as one word.
