### ISSUE TITLE
Add Autorun/AutoRun and Autoplay/AutoPlay entries

### ISSUE THREAD

**Issue by Nick-FitzGerald** [MicrosoftDocs/microsoft-style-guide#236]
Google shows these terms are not used particularly consistently across MS-authored content (although AutoPlay is a lot more consistently used than other casing for that word). definitive entries explaining the correct usage of each would be very helpful for third-party authors who wish to follow Microsoft's guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/#feedback)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by maitesadaba** [comment]
Hello,

Thanks a lot for your feedback. Let me look into this and I will come back to you.

Have a lovely day!
Maite

From: Nick-FitzGerald ***@***.***>
Sent: Thursday, May 6, 2021 4:38 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] Add Autorun/AutoRun and Autoplay/AutoPlay entries (#236)


Google shows these terms are not used particularly consistently across MS-authored content (although AutoPlay is a lot more consistently used than other casing for that word). definitive entries explaining the correct usage of each would be very helpful for third-party authors who wish to follow Microsoft's guidance.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
  *   Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
  *   Content: Welcome - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fwelcome%2F%23feedback&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615515243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oLjhWCr2Bw9EO9dkLWcAF3E9WEsf4GXCrx%2FGqXAFPQs%3D&reserved=0>
  *   Content Source: styleguide/welcome/index.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fwelcome%2Findex.md&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615520232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nc4l%2FZAJxo2%2Bu9mVKdgQg8rPZ13MwCSJL4fTCF1hMc0%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615525226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xi3UULPrNu8hF7AiBvhODxuOqExGmC2XInDE5aXM8nc%3D&reserved=0>
  *   Microsoft Alias: pallep

**Comment by maitesadaba** [comment]
Hi Nick,

The guidance in the Microsoft Writing Style Guide is to avoid internal capitalization (such as AutoScale or e-Book) unless it's part of a brand name.

Capitalization - Microsoft Style Guide | Microsoft Docs<https://docs.microsoft.com/en-us/style-guide/capitalization>

Let us know if you have any other questions.

Maite

Maite Sadaba Champetier de Ribes (SDL*)
CELA Global Readiness
***@***.******@***.***> | +32 16 79 00 36


Global Readiness Home<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fsites%2Fglobalreadiness&data=02%7C01%7Cv-mebell%40microsoft.com%7C982f24c3f8e0477bf03508d7af120dbc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637170364383693084&sdata=s8ThzwO2dWlUmrTp4LvN4E%2FhVZlGHQg8h5tphmbNMjI%3D&reserved=0>
Global Readiness Inquiry (questions, comments, requests<http://webdefence.global.blackspider.com/urlwrap/?q=AXicJY_bTgIxEIbrwyx3lmm70GJCFCWGVePhkst220Jld7u2BcU38N4H8MJ38nUskMwhmf-b_DNnM3T3i9DfD0Kh2YNQOIYdbqVrat-l4Btc-xbB9eIxqVQDoQwYaqPUUsmrqE_yOqU-XgyHnWxhjKO0pnHdJuI--GTq5HyH_TY13m8O-PByG5rpcadgs4Le5lj170a57m3rwp4CEVh-boPJs-iSibgzKUPVSccy9h8DLZOcAi34DZBcduetUaZpihJaVwcfvU0HsyxNBLW0rJkVBkrOlQU2AqG5tISCVnVGOLUTIZQVY0tKIu2ESEU1rzUQolXJM3IwgZxjxgkHNi6ZYLkDF4N4vGX_Wj4s85WLttx5vhyFzWp17_Rc59_21eLOrauJF8_rlyfiqoLNB8FEE3ZGTwEh9PWN0D_xC31C&Z>



From: Nick-FitzGerald ***@***.***>
Sent: Thursday, May 6, 2021 4:38 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] Add Autorun/AutoRun and Autoplay/AutoPlay entries (#236)


Google shows these terms are not used particularly consistently across MS-authored content (although AutoPlay is a lot more consistently used than other casing for that word). definitive entries explaining the correct usage of each would be very helpful for third-party authors who wish to follow Microsoft's guidance.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
  *   Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
  *   Content: Welcome - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fwelcome%2F%23feedback&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615515243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oLjhWCr2Bw9EO9dkLWcAF3E9WEsf4GXCrx%2FGqXAFPQs%3D&reserved=0>
  *   Content Source: styleguide/welcome/index.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fwelcome%2Findex.md&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615520232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nc4l%2FZAJxo2%2Bu9mVKdgQg8rPZ13MwCSJL4fTCF1hMc0%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7C7264ee1288d04a10961908d91037e99f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637558654615525226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xi3UULPrNu8hF7AiBvhODxuOqExGmC2XInDE5aXM8nc%3D&reserved=0>
  *   Microsoft Alias: pallep
