### ISSUE TITLE
Broken markdown table

### ISSUE THREAD

**Issue by osisoft-mbishop** [MicrosoftDocs/microsoft-style-guide#237]
The markdown table under the last heading needs fixing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
* Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
* Content: [Hyphens - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)
* Content Source: [styleguide/punctuation/dashes-hyphens/hyphens.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/dashes-hyphens/hyphens.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by maitesadaba** [comment]
Thank you for your feedback, Mark. This has now been fixed.

Have a lovely day!
Maite

From: Mark B ***@***.***>
Sent: Tuesday, May 11, 2021 3:36 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] Broken markdown table (#237)


The markdown table under the last heading needs fixing.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
  *   Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
  *   Content: Hyphens - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fpunctuation%2Fdashes-hyphens%2Fhyphens&data=04%7C01%7Cv-maites%40microsoft.com%7Cc0f71fd88a24467a11bf08d9141d26de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637562937714110770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DQL2KVEx1QHx0qyWvO0p8lTnI8NhYx4%2FQABc8e2yjSE%3D&reserved=0>
  *   Content Source: styleguide/punctuation/dashes-hyphens/hyphens.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fpunctuation%2Fdashes-hyphens%2Fhyphens.md&data=04%7C01%7Cv-maites%40microsoft.com%7Cc0f71fd88a24467a11bf08d9141d26de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637562937714120766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v6UbwpzW7eBLpTtQIcvyuCmanSSh5c3Yr%2FneF98VUdk%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7Cc0f71fd88a24467a11bf08d9141d26de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637562937714120766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6xaY8YKzAoREjYyYlm4CPyVcNX7OgXsKW9yd8roDzM%3D&reserved=0>
  *   Microsoft Alias: pallep
