### ISSUE TITLE
time to drop the hyphen?

### ISSUE THREAD

**Issue by cru121** [MicrosoftDocs/microsoft-style-guide#242]
https://docs.microsoft.com/en-us/search/?scope=Style%20guide&terms=plugin
Looks like you guys are not using the hyphen too much. Is it the right time to remove it also from the style guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0e7afd-1d7b-9594-173a-6745b870c2f3
* Version Independent ID: a996c9a5-bcb2-ed2f-f178-9ff6ba83aa07
* Content: [plug-in - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/plug-in)
* Content Source: [styleguide/a-z-word-list-term-collections/p/plug-in.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/p/plug-in.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pivic** [comment]
@cru121: you either need to read the [Hyphens](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens) section or read on how hyphenation works in the English language; compound modifiers, etc.

There's a difference between an operating-system guide and an operating system guide.

**Comment by cru121** [comment]
Thanks for your concerns. For reference, looks like Google is already removing the hyphen:
https://developers.google.com/style/word-list#letter-p
**plugin (noun), plug-in (adjective), plug in (verb)**
