### ISSUE TITLE
Usage of API

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/microsoft-style-guide#247]
I was looking for API and guidance on how to use it. For example... When should API be singular vs. plural? If API is singular for a given app or service, what are the individual components of an API called--functions? 

I'd love to see a standalone entry for API, perhaps cross-linked with https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/interface. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1edf80c-add4-ab9a-11dc-b699d7ecbcd6
* Version Independent ID: b9bfe3c5-acd4-6293-fe3b-06657ee99e48
* Content: [app, application - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/app-application)
* Content Source: [styleguide/a-z-word-list-term-collections/a/app-application.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/a/app-application.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pivic** [comment]
Hey there, @redmondChris. I'm not with the MS Writing Style Guide Team, but I work as technical writer.

In my experience, when spelling out acronyms like 'API', you find out how to use it in the singular and plural. In this case, API stands for 'application programming interface', i.e. *one* interface. To create a plural form, we add an 's' to the end: APIs.

**Comment by redmondChris** [comment]
Thanks @pivic. I don't think I asked my question well. My question wasn't how to make API plural, but when to. Perhaps another approach would be to ask for the definition of interface, which I think is confused with a function.

The reason I ask is that I keep seeing the use of "API" to describe just one function, and then "APIs" used to describe the single set of defined functions. As an example, someone might say "use the GetClientName, GetClientAddress, and GetClientPhone APIs." What I think they should be saying is "use the GetClientName, GetClientAddress, and GetClientPhone functions [or calls, or methods] in the blahblah API." 

If I'm correct, then it seems odd to me is that I have only found a few API definitions online that even refer to all these elements--and some of the definitions get it wrong, too. I think adding this clarity in the Microsoft style guide would help educate and clarify, both for writers (including PMs like me who do some of the writing) and their audience members.
