### ISSUE TITLE
Usage of biased Words

### ISSUE THREAD

**Issue by shankarrevadala** [MicrosoftDocs/microsoft-style-guide#248]
[Enter feedback here]
Hi Team,

Per the recent updates and guidelines, technical writers should not use certain biased words such as whitelist, blacklist, master, and slave in documentation. I believe the same is applicable while writing user interface text. In fact, those words should not be used anywhere.

Please clarify. Thanks in advance.

Regards,
Shankar Revadala
Senior Technical Writer,
Commvault, Bangalore (India)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a09d7650-47d1-1315-9899-0c8c2ede75cb
* Version Independent ID: 7e1c7ede-8eed-c87d-8548-f269a99c3f2a
* Content: [whitelist - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/whitelist)
* Content Source: [styleguide/a-z-word-list-term-collections/w/whitelist.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/w/whitelist.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by maitesadaba** [comment]
Hi there,

You are completely right, the bias-free communication topic applies to all types of communications, and it is not only applicable to technical writers:

Bias-free communication - Microsoft Style Guide | Microsoft Docs<https://docs.microsoft.com/en-us/style-guide/bias-free-communication>

Thank you!
Maite

From: shankarrevadala ***@***.***>
Sent: Wednesday, June 30, 2021 7:53 PM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [MicrosoftDocs/microsoft-style-guide] Usage of biased Words (#248)


[Enter feedback here]
Hi Team,

Per the recent updates and guidelines, technical writers should not use certain biased words such as whitelist, blacklist, master, and slave in documentation. I believe the same is applicable while writing user interface text. In fact, those words should not be used anywhere.

Please clarify. Thanks in advance.

Regards,
Shankar Revadala
Senior Technical Writer,
Commvault, Bangalore (India)

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: a09d7650-47d1-1315-9899-0c8c2ede75cb
  *   Version Independent ID: 7e1c7ede-8eed-c87d-8548-f269a99c3f2a
  *   Content: whitelist - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fa-z-word-list-term-collections%2Fw%2Fwhitelist&data=04%7C01%7Cv-maites%40microsoft.com%7C185e5ba201dd44b489b508d93befe411%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606723815034875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GD82p0vNEJklgKVZpFncxYr53%2BoKCNSx%2BVFNxTLeSK0%3D&reserved=0>
  *   Content Source: styleguide/a-z-word-list-term-collections/w/whitelist.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fa-z-word-list-term-collections%2Fw%2Fwhitelist.md&data=04%7C01%7Cv-maites%40microsoft.com%7C185e5ba201dd44b489b508d93befe411%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606723815034875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lOc7vfdRQFpRchsyrwph4iM2VsboG05I7IrdvKWF%2Fm8%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7C185e5ba201dd44b489b508d93befe411%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606723815044870%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8S1KeoQvx%2Fi3qaqWaqczEof50A7z2SSkPs6XD59LoLo%3D&reserved=0>
  *   Microsoft Alias: pallep

**Comment by shankarrevadala** [comment]
Hi Maite,

Thanks for the response. I started the thread to get confirmation on using
bias-free text on the user interface (such as error messages, tool tips,
and so on).

Regards,
Shankar Revadala
