### ISSUE TITLE
Examples are not distributed to cover all the guidelines

### ISSUE THREAD

**Issue by ahungund** [MicrosoftDocs/microsoft-style-guide#25]
Both examples are for "switch" usage (instead of "toggle" as a verb), while there are no examples for "toggle" as an adjective.
 It would probably be better to add at least one example for each guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a3e1d-962a-db8a-06c6-725f723a62ce
* Version Independent ID: 3f696e13-953c-e0c0-6ffa-59792ae85dab
* Content: [toggle - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/t/toggle)
* Content Source: [styleguide/a-z-word-list-term-collections/t/toggle.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/t/toggle.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
We recently updated the [toggle](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/t/toggle) guideline to include better examples. Thanks and hope this helps.
