### ISSUE TITLE
Another Github link instead of docs.microsoft.com link

### ISSUE THREAD

**Issue by CRZ** [MicrosoftDocs/microsoft-style-guide#259]
Clicking on the "Date and time terms" link takes you to Github and a 404 not found error.  This appears to be the same issues as on the "What's New" page and may be in other places in the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940e15a9-149b-04fc-4cab-186a48bbe874
* Version Independent ID: 779b9d15-f811-2da7-ae4a-62874ba79446
* Content: [Colons - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/colons)
* Content Source: [styleguide/punctuation/colons.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/colons.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
This has been addressed, thanks!
