### ISSUE TITLE
Body text or <p> CSS styling for web content

### ISSUE THREAD

**Issue by tallis636yahoo** [MicrosoftDocs/microsoft-style-guide#26]
[ I cannot find in the style guide best practice (CCS) for body font size, weight, and color. I DO see  "minimum" line spacing for various font sizes (e.g. 14 pt body text - 120% line spacing minimum).
As an example, for a SharePoint Text web part, what are some guidelines for  body text <p> style and font-weight?

I believe the online Microsoft Writing Style Guide, styles the <p> text/ body text as following:  
font-size: 16px
font-weight: 400
line-height: 160%
color: rgb (0,0,0)
I am thankful for any insight, opinions, or guidance you can provide. 

Tallis Lockos]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi Tallis,
In general, the Microsoft Writing Style Guide covers editorial issues like word choice, capitalization, and punctuation. A site's web or UI designer is the best resource for the details of text styling, like font and font size. 

I'm also replying to your question in a separate email in more detail.
