### ISSUE TITLE
What's New links do not correctly convert to PDF

### ISSUE THREAD

**Issue by CRZ** [MicrosoftDocs/microsoft-style-guide#266]
In the current PDF version of the guide, the more recent (August) links in the What's New section are hyperlinks to docs.microsoft.com instead of links which jump you to the relevant PDF section, as the May and earlier links are in What's New.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by CRZ** [comment]
Happy six months since I reported this!

Links are still inconsistent in the PDF version.

**Comment by S-LRaillard** [comment]
Hi @CRZ , I am working on addressing this issue, which seems to stem from migration issue in the What's new section. I'm replacing links individually, but this will take a while. Please bear with me, thanks!
