### ISSUE TITLE
Please define "resource"

### ISSUE THREAD

**Issue by NatalieLias** [MicrosoftDocs/microsoft-style-guide#270]
The cloud-computing terms page refers to "resources" but this term is itself undefined in the style guide, and it needs to be, especially compared and contrasted with "devices". 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6224ee62-e768-c9fd-dff0-110ec8e88829
* Version Independent ID: 06a82dbc-3330-62de-d558-301e14f68afc
* Content: [Cloud-computing terms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/cloud-computing-terms)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/cloud-computing-terms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/term-collections/cloud-computing-terms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for your feedback. This has been added to our backlog, @NatalieLias
