### ISSUE TITLE
Device agnostic term to use instead of "double-click" or "double-tap".

### ISSUE THREAD

**Issue by emmacassidy** [MicrosoftDocs/microsoft-style-guide#273]
Please can you provide a device agnostic term to use instead of "double-click" or "double-tap".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df353f5e-5a0a-293f-53cb-a87cb2296040
* Version Independent ID: 8440cb37-1384-c86a-a12c-7e9d6b924b46
* Content: [Describing alternative input methods - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods)
* Content Source: [styleguide/procedures-instructions/describing-alternative-input-methods.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/procedures-instructions/describing-alternative-input-methods.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pivic** [comment]
I think Microsoft only apply 'click' to mouse interactions.

**Comment by S-LRaillard** [comment]
That's correct - @pivic @emmacassidy , Microsoft only uses "click" to refer to physical mouse interactions. I encourage you to refer to https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods for more information.
