### ISSUE TITLE
Use 'select' instead of 'pick'

### ISSUE THREAD

**Issue by pivic** [MicrosoftDocs/microsoft-style-guide#278]
This page contains 'pick' but should instead probably contain 'select'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa26d2e-2b59-03e9-f674-12231aa958d2
* Version Independent ID: 01947c90-5b11-d24d-437b-ae04032e2dc1
* Content: [dropdown - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dropdown)
* Content Source: [styleguide/a-z-word-list-term-collections/d/dropdown.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/d/dropdown.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @pivic and thanks for your feedback. The debate about "select," "choose," "pick" and related terms is always ongoing in the MWSG. We will add this to the backlog of considerations :)
