### ISSUE TITLE
Disagreement of plural case

### ISSUE THREAD

**Issue by LawrenceNormie** [MicrosoftDocs/microsoft-style-guide#284]
> Though the content for developers and IT professionals tends to be more technical than that for a general audience, the fundamentals of the Microsoft brand voice still apply.

Disagreement of plural case ("fundamentals" and "applies"):
"...the fundamentals of the Microsoft brand voice still applies" => "...the fundamentals of the Microsoft brand voice still apply"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e31cde7a-3436-1c47-f9df-514aef04cace
* Version Independent ID: 84bdd844-c4e4-c603-b5c3-8cd85b4e094b
* Content: [Developer content - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/developer-content/)
* Content Source: [styleguide/developer-content/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/developer-content/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @LawrenceNormie thanks for your feedback - this appears to have been fixed a while ago.
