### ISSUE TITLE
Dialog box or dialog?

### ISSUE THREAD

**Issue by Nytechwriter** [MicrosoftDocs/microsoft-style-guide#285]
The alphabetical list of terms expresses a preference for _dialog_, rather than _dialog box_, but "Describing interactions with the UI" uses "Dialog boxes" in the **Close** row. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ad46ad-342d-da22-47a6-504ce7a06a95
* Version Independent ID: 3f8c7233-e250-e7f7-faff-c90b91ff03c7
* Content: [Describing interactions with UI - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)
* Content Source: [styleguide/procedures-instructions/describing-interactions-with-ui.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/describing-interactions-with-ui.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by vastbluesky** [comment]
I noticed the same discrepancy. The [Formatting text in instructions](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions) page also uses "dialog box" in an example of correct usage.

**Comment by S-LRaillard** [comment]
This issue has been fixed!
