### ISSUE TITLE
The colon is rendered as "&#58;"

### ISSUE THREAD

**Issue by chanakavp** [MicrosoftDocs/microsoft-style-guide#287]
![image](https://user-images.githubusercontent.com/16893134/152837770-ec34a350-7835-4562-b500-baa7128d94c9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
This has been fixed @chanakavp , thanks for your feedback.
