### ISSUE TITLE
Use of 'box' for 'list box'

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/microsoft-style-guide#29]
In my travels, most devs seem to refer to the 'drop-down list box' as just a 'drop-down list' (no 'box' at the end). I suggest calling out if 'box' is required.

> For other audiences, use box if you must name the UI element.

I'm suggesting that this instruction is slightly confusing: Can the remark be clarified to say if 'box' is required; if so, exactly under what circumstances?

> In developer documentation, refer to the UI element as a \*drop-down list\*. For other audiences, refer to the UI element as a \*drop-down list box\*.

[I can send a PR if you like the suggestion.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3340762-f756-bbdc-1bb9-56267ddfead8
* Version Independent ID: 03695a4f-a05d-8b19-033d-78881fb9a8ad
* Content: [drop-down - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/drop-down)
* Content Source: [styleguide/a-z-word-list-term-collections/d/drop-down.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/d/drop-down.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by guardrex** [comment]
Hi @camind ... that's cool, but I don't think that answers my question wrt "*drop down list*." Perhaps, I'm looking at the wrong topic/wrong control.

Is "*drop down list*" permissible? If so under certain circumstances, what circumstances? 

![drop-down](https://user-images.githubusercontent.com/1622880/52014630-a5b7ca00-24a5-11e9-9986-7206eb8e0be3.png)

**Comment by camind** [comment]
"Drop-down list" would be OK in content for developers when you need to specify what kind of list it is. For all other users, if you need to refer to what kind of control it is, just "box" would be preferable.

**Comment by guardrex** [comment]
Ok, thanks.
