### ISSUE TITLE
Offensive recommendations - Person first language

### ISSUE THREAD

**Issue by Unnamed-Variable** [MicrosoftDocs/microsoft-style-guide#290]
The style guide when talking about disabilities suggests Person first language such as a "Person with deafness" and "Person with autism".  The "Person" comes before the disability.

APA style directly recommends against both of these specific examples and for good reason.  Disabled communities have different views on the topic of "person first language", and many of them find the phrasing to be convoluted, condescending, and euphemistic and something foisted onto them without their input by well meaning editors.  The deaf and autistic communities have pretty consistently preferred identity-first language in general.  In other communities, such as those for people with intellectual disabilities, person-first phrasing remains preferred.  Further, individuals within these communities will disagree about which phrasing is more appropriate just to muddle the waters further.

I would recommend a rewrite of this entire section, and I would totally disregard the Microsoft Style guides recommendation until a rewrite is done because the current recommendations are likely to cause offence.  One would be wise to do a bit of research about the disabled people and disabled community you're talking about to find their preferences regarding how they would like to be referred to.  One should pay attention to how the disabled people you're talking about refer to themselves.  Suggesting that every disabled person should be referred to by "Person first language" is simply bad advice and is likely to cause offence, and further risks an editor correcting a disabled writer who refers to themselves by identity-first language which will DEFINITELY cause offence. 

The style guide should emphasize how people and communities have different views on this subject, and the need to ask the relevant person or group being discussed for advice on this topic.  Some superior alternatives to Microsofts style recommendations that I think are quite thoughtful and reasonable:
https://apastyle.apa.org/style-grammar-guidelines/bias-free-language/disability
https://ncdj.org/style-guide/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47aaf3f0-fad9-7969-f4a6-687ff23e5315
* Version Independent ID: 2df604ee-8963-1bc6-e68a-e7cc985b9e2d
* Content: [Accessibility terms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/accessibility-terms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/term-collections/accessibility-terms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for your thoughtful feedback @Unnamed-Variable . This topic has been under consideration and revision recently, and we expect updates shortly to align with nuanced guidance provided by accessibility experts. We wholeheartedly agree that the preferences of the person or community being talked about should be respected whenever these are known. However, we simply do not have this context when discussing disability issues at the global level or in the abstract, which means that a default recommendation for inclusive language will always be made, in the absence of other information.
