### ISSUE TITLE
Bold when....

### ISSUE THREAD

**Issue by JRosioKR** [MicrosoftDocs/microsoft-style-guide#291]
Under **Bold**, Please include specific directions about what words in specific contexts should be bold in technical documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627424f9-1793-628f-e3ab-47f904d87bf8
* Version Independent ID: d0d2f755-9559-d90b-e972-21596751d987
* Content: [bold - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/bold)
* Content Source: [styleguide/a-z-word-list-term-collections/b/bold.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/b/bold.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
Maybe you're searching for something like https://docs.microsoft.com/style-guide/developer-content/formatting-developer-text-elements ?

**Comment by JRosioKR** [comment]
Perfect! This is exactly what I need. Thank you.
