### ISSUE TITLE
Broken links at bias-free-communication.md

### ISSUE THREAD

**Issue by OutSystemsAMM** [MicrosoftDocs/microsoft-style-guide#293]
[Enter feedback here]
The links to "Accessibility guidelines and requirements", "Global communications",  "Accessibility term collection" all land on a git 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3fbd78-e2ad-bfc6-9f2f-13f739b57937
* Version Independent ID: 9ce3e837-12b6-e7b8-6bef-597ec2570dbb
* Content: [Bias-free communication - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/bias-free-communication)
* Content Source: [styleguide/bias-free-communication.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/bias-free-communication.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by DonGlover** [comment]
@OutSystemsAMM @S-LRaillard has fixed this see issues 325 and 337.

**Comment by S-LRaillard** [comment]
Thanks @DonGlover  - yes the broken links issue was fixed a while ago, please close this ticket @OutSystemsAMM :)
