### ISSUE TITLE
404 error on Accessibility term collection

### ISSUE THREAD

**Issue by AndySager** [MicrosoftDocs/microsoft-style-guide#295]
The link to the Accessibility term collection returns a 404 error. Relevant sentence below:

Don't mention a disability unless it's relevant. For more information, see the [Accessibility term collection](https://github.com/MicrosoftDocs/microsoft-style-guide-pr/blob/main/styleguide/a-z-word-list-term-collections/term-collections/accessibility-terms.md).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3fbd78-e2ad-bfc6-9f2f-13f739b57937
* Version Independent ID: 9ce3e837-12b6-e7b8-6bef-597ec2570dbb
* Content: [Bias-free communication - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/bias-free-communication?source=docs)
* Content Source: [styleguide/bias-free-communication.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/bias-free-communication.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
I'm sorry I missed this comment - but this link issue has since been fixed @AndySager , you can close the ticket. Thanks!
