### ISSUE TITLE
Inactive state

### ISSUE THREAD

**Issue by chitpot27** [MicrosoftDocs/microsoft-style-guide#30]
Why i im inactive state kindly help me thanx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54fea166-bd7a-7242-29ca-cefc6ad0a660
* Version Independent ID: 60125e2a-7b18-341f-4875-bb436bd54967
* Content: [inactive, inactive state - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/inactive-inactive-state)
* Content Source: [styleguide/a-z-word-list-term-collections/i/inactive-inactive-state.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/i/inactive-inactive-state.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
I'm sorry, I don't understand your question.
Can you tell me more about the problem that you are having?
Thanks!
Catherine
