### ISSUE TITLE
The ratio symbol used for clock time

### ISSUE THREAD

**Issue by olafbacon** [MicrosoftDocs/microsoft-style-guide#303]
Use the ratio symbol Unicode 2236 (alt+2236) as the delimiter between hours, minutes, and seconds, rather than the standard colon (Unicode 003A).
The ratio symbol is not listed in the illustrated symbols. How are we to get this? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9ce006-d5ab-9155-9019-b329791bcfd2
* Version Independent ID: 3b8f6bb8-a499-0bad-d2d7-2e17af1afebd
* Content: [Special characters - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/special-characters)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/special-characters.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/term-collections/special-characters.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
Type Alt+2236 on your numpad.

**Comment by Jay-o-Way** [comment]
In this case, the solution is mentioned on page https://docs.microsoft.com/en-us/style-guide/punctuation/slashes

> When you instruct customers to enter a slash, always include the spelled-out term (backslash or slash) first, followed by the symbol in parentheses.

So: `Use the ratio symbol Unicode 2236 (alt+2236)` --> `Use the ratio symbol (∶) Unicode 2236 (alt+2236)`
