### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by holhau** [MicrosoftDocs/microsoft-style-guide#305]
Hi Team 
In this paragraph:
Focus on people, not disabilities. For example, talk about readers who are blind or have low vision and customers with limited dexterity. Don't use words that imply pity, such as stricken with or suffering from. Don't mention a disability unless it's relevant. For more information, see the [Accessibility term collection](https://github.com/MicrosoftDocs/microsoft-style-guide-pr/blob/main/styleguide/a-z-word-list-term-collections/term-collections/accessibility-terms.md).
The link to the Accessibility Term Collection takes you to a page with a 404 error.
thanks
Holly 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3fbd78-e2ad-bfc6-9f2f-13f739b57937
* Version Independent ID: 9ce3e837-12b6-e7b8-6bef-597ec2570dbb
* Content: [Bias-free communication - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/bias-free-communication)
* Content Source: [styleguide/bias-free-communication.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/bias-free-communication.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by DonGlover** [comment]
@holhau @S-LRaillard has fixed this. See issues 325 and 337.
