### ISSUE TITLE
Accelerator Keys

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/microsoft-style-guide#31]
There is no listing for accelerator keys. 

See https://docs.microsoft.com/en-us/windows/desktop/menurc/about-keyboard-accelerators

About Keyboard Accelerators
05/30/2018
7 minutes to read
Accelerators are closely related to menus — both provide the user with access to an application's command set. Typically, users rely on an application's menus to learn the command set and then switch over to using accelerators as they become more proficient with the application. Accelerators provide faster, more direct access to commands than menus do. At a minimum, an application should provide accelerators for the more commonly used commands. Although accelerators typically generate commands that exist as menu items, they can also generate commands that have no equivalent menu items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1379cffc-1742-f6f9-0cb2-5612d74bc538
* Version Independent ID: 310bb5bf-fd65-3a31-70f2-6ec838444087
* Content: [Keys and keyboard shortcuts - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts#feedback)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
The [Keys and keyboard shortcuts](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts) topic, in the first row of the table, includes guidelines for the term *accelerator key.* 

In Microsoft style, *keyboard shortcut* is preferred to *accelerator key.*

Thanks, and I hope that helps.
Catherine

**Comment by alex20850** [comment]
I am trying to get Microsoft the better document the keyboard shortcuts that access the menus.How would I refer to the menu commands such as Alt,F,S as different from Ctrl+S?There are hundreds more Alt commands for the menus than the keyboard shortcuts like Ctrl+S. Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm
