### ISSUE TITLE
The fourth and final example doesn't include sign in or sign out.

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/microsoft-style-guide#313]
The fourth and final example on this page, included below, is confusing, as it neither contains _sign in_ nor _sign out_.

"Some networks can be set up to remember your username and password."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72348d28-62c9-91b5-4dfa-b5e74c4c7c8e
* Version Independent ID: 89199b13-a047-8f74-364d-8e685a1e53c8
* Content: [sign in, sign out - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/sign-in-sign-out)
* Content Source: [styleguide/a-z-word-list-term-collections/s/sign-in-sign-out.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/s/sign-in-sign-out.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi there,
This is a great piece of feedback; the topic has now been updated without that confusing last example.
