### ISSUE TITLE
Use accurate grammatical terminology

### ISSUE THREAD

**Issue by mschnell-qontigo** [MicrosoftDocs/microsoft-style-guide#318]
The terms _subject_ and _object_ seem to be misused in the article on **Download**, which includes the following sentence:

> In grammatical terms, use both a subject (the thing to be downloaded) and an object (the thing the subject is downloaded to) with the verb download.

Usually, the thing downloaded would not be the subject, but the direct object, and the place the thing is downloaded to would be part of an adverbial phrase: 

> Download the data to your hard drive.

_Data_ (the object of the verb _download_) is the downloaded thing, and _hard drive_ (part of the adverbial phrase _to your hard drive_) is the destination of the downloaded thing. (Although _hard drive_ is the object of a preposition, the article seems to suggest that _hard drive_ will be the object of the verb _download_.)

I suggest deleting the sentence on grammatical terms. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e54b178-b72f-eadd-c843-ed5bb8b62dab
* Version Independent ID: 2aec2a97-4a24-2497-6f70-6fff8ef2fbfe
* Content: [download - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/download#feedback)
* Content Source: [styleguide/a-z-word-list-term-collections/d/download.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/d/download.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for this helpful feedback. This issue has now been fixed; please close this ticket @mschnell-qontigo
