### ISSUE TITLE
Hierarchical Menus

### ISSUE THREAD

**Issue by kai687** [MicrosoftDocs/microsoft-style-guide#319]
A very small detail, but I'm wondering if you're not contradicting yourselves on this page?

What you recommend is: 

> don't bold the `>` character.

So: `<strong>Menu</strong> &gt; <strong>Submenu</strong>` would be correct.

The example in the same column makes the whole path bold though: 
`<strong>Accounts &gt; Other accounts &gt; Add an account</strong>`

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ad46ad-342d-da22-47a6-504ce7a06a95
* Version Independent ID: 3f8c7233-e250-e7f7-faff-c90b91ff03c7
* Content: [Describing interactions with UI - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)
* Content Source: [styleguide/procedures-instructions/describing-interactions-with-ui.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/describing-interactions-with-ui.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
_lol_ good point. It should not be in bold.

**Comment by S-LRaillard** [comment]
Hi,
This issue has now been fixed - thanks for your helpful feedback. @kai687 can you please close the ticket?
