### ISSUE TITLE
Come back!

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/microsoft-style-guide#320]
@maitesadaba @camind @v-anpasi @pallep
Looks like you guys lost the password to this repo or something? Issues, prs and content haven't had any real update in years! How is that possible???

**Comment by DonGlover** [comment]
For the most part, they fired most of the editors years ago and gutted most of the editorial board. Many of the senior people left who were interested in trying to maintain the board and quality have essentially been driven from the company.

**Comment by Jay-o-Way** [comment]
Typycal damn Microsoft 😖

**Comment by DonGlover** [comment]
@Jay-o-Way It looks like they are showing some love for the style guide today! @S-LRaillard
