### ISSUE TITLE
ratio symbol should be used as delimiter in time

### ISSUE THREAD

**Issue by ankap18** [MicrosoftDocs/microsoft-style-guide#321]
Use the ratio symbol Unicode 2236 (alt+2236) as the delimiter between hours, minutes, and seconds, rather than the standard colon (Unicode 003A).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88ebe26-c748-e668-4b55-42b87fd9c86e
* Version Independent ID: da313f5c-fec4-990d-0ae2-185ff6a894e7
* Content: [En dashes - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/enes)
* Content Source: [styleguide/punctuation/dashes-hyphens/enes.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/punctuation/dashes-hyphens/enes.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
True. Related to #304

**Comment by Jay-o-Way** [comment]
From the top of my head, I remember the entire guideline is X-ed
