### ISSUE TITLE
Correction for the "Don't use verbs as nouns" section

### ISSUE THREAD

**Issue by developedbyataah** [MicrosoftDocs/microsoft-style-guide#323]
In the last point ("don't use verbs as nouns or nouns as verbs"), the third example ("respond to the ask"), is grammatically incorrect and breaks away from the "verb then noun" pattern followed by the previous two examples.

My assumption is that "respond to the question" would still be the proper "Not this:" for "respond to the request"

* I know it's a minor issue--just trying to keep the concepts easily digestible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18cd8a3a-3ca8-0135-6cbd-2b2b22ec6fd7
* Version Independent ID: 908ff080-6afc-4806-d679-196bee317c08
* Content: [Don't use common words in new ways - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/word-choice/dont-use-common-words-in-new-ways)
* Content Source: [styleguide/word-choice/dont-use-common-words-in-new-ways.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/word-choice/dont-use-common-words-in-new-ways.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
I believe "request" is both a verb and a noun

**Comment by brittanyshands** [comment]
Don't forget about "skilling." Seeing that one a lot lately and it hurts my brain.

**Comment by S-LRaillard** [comment]
Hi @developedbyataah,
You are correct that "respond to the ask" is grammatically incorrect - it is being used as an example of what not to do. Are you also objecting to "respond to the request"? "Request" can be both a verb and a noun and is therefore correct in this example (according to the American Heritage Dictionary, it is defined in the noun sense as "something asked for").
