### ISSUE TITLE
How do you refer to the hamburger menu?

### ISSUE THREAD

**Issue by nadinemurray** [MicrosoftDocs/microsoft-style-guide#326]
Do you folks have a definitive term for the "hamburger menu"? https://en.wikipedia.org/wiki/Hamburger_button

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi there! The MWSG is actually not responsible for standardizing the names of UI elements. The Fluent Design team would be your best bet for that. I have seen it referred to as a navigation pane or a navigation menu.
