### ISSUE TITLE
The ampersand: when to use?

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/microsoft-style-guide#334]
Just had a small back-and-forth with Niels about using the ampersand in a UI title / or not. He pointed out it's commonly used in Windows 11 Settings, but then I found this page. Is Miscrosoft actually contradicting its own Guide???

![Ampersand in a title in Win11 Settings.](https://user-images.githubusercontent.com/9866362/183284923-f9e3fee9-c589-4db9-ab05-68f748a7d336.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57887604-1a2d-6860-4936-91c1ea23a51e
* Version Independent ID: e1303873-654b-e2e6-d3e3-6c1269d0a5cd
* Content: [Ampersand (&) - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/ampersand)
* Content Source: [styleguide/a-z-word-list-term-collections/a/ampersand.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/a/ampersand.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by DonGlover** [comment]
If I interpret your question correctly, it appears that you are looking at an "apples and oranges" situation.
In UI (ie in apps, both desktop, and web) & is commonly used to save on space. 
BUT, the page in question is addressing usage its usage in technical content (overviews, walkthroughs, how tos, etc). These are two different contexts. In UI it is generally accepted in content it is not UNLESS you are referring to the UI that uses it OR it is necessary to convey how to accomplish the task accurately.

**Comment by Jay-o-Way** [comment]
I see. Guess you have a point.

**Comment by Jay-o-Way** [comment]
Is there a guidance page for UI, that covers things like the ampersand, then?

**Comment by DonGlover** [comment]
@Jay-o-Way Simple answer is probably yes, but it is likely maintained on a per product group level internally.

**Comment by S-LRaillard** [comment]
Hi there,
You can find some relevant information about the use of the ampersand under the topic "[ampersand (&)](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/ampersand)". Hope this helps!
