### ISSUE TITLE
Define 'window'

### ISSUE THREAD

**Issue by doc411** [MicrosoftDocs/microsoft-style-guide#336]
In the **A to Z word list and term collections**, it would be useful to have a definition of _window_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8a876b-9077-9c9e-b7ec-1a61c0bfa86e
* Version Independent ID: d0c34316-ed6d-8e54-15be-f37dac9ffc46
* Content: [window - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/window)
* Content Source: [styleguide/a-z-word-list-term-collections/w/window.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/w/window.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by DonGlover** [comment]
Definition in this context? Or in general?
What is the confusion that would addressed?

**Comment by S-LRaillard** [comment]
Thank you for your feedback. It would be helpful to get more context, as noted above.
