### ISSUE TITLE
Due to, because of, or something else? 

### ISSUE THREAD

**Issue by Kuch-Y** [MicrosoftDocs/microsoft-style-guide#339]
[Enter feedback here] I could not find your recommendation on whether to use due to, because of, or something else. 
If this is addressed, please point me to the content. If not, please advise and address this in your style guide. My company uses your style guide for general style guidelines not covered in our style guide so having the word from Microsoft would really help this editor. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi Kuch-Y,

I am the Editor to the Microsoft Writing Style Guide. Thank you for providing feedback on this. 

The MWSG does not provide guidance on basic grammar and syntax, but aligns itself loosely with the Chicago Manual of Style (see the bullet point on the page "Microsoft style references: For answers to style questions not covered in this guide or general questions about grammar and punctuation, see [The Chicago Manual of Style](http://www.chicagomanualofstyle.org/home.html).

As such, we have no specific recommendation on this issue other than to stay crisp, relaxed and simple.
