### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lb185064** [MicrosoftDocs/microsoft-style-guide#343]
[Enter feedback here]
Greetings,

See the following entry. Please either remove the period after "examples." or else change it to a comma. Recommend changing "gap" to "gaps," or else add the article "the" before the word "gap."
<html>
<body>

May 13, 2022 | Lists | Added another example of a bulleted list. Expanded the Exception and added examples. to address gap in guidance regarding lists that do not complete an introductory phrase, but whose items are all short, complete sentences.
-- | -- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**May 13, 2022	[Lists](https://docs.microsoft.com/en-us/style-guide/scannable-content/lists)	Added another example of a bulleted list. Expanded the Exception and added examples. to address gap in guidance regarding lists that do not complete an introductory phrase, but whose items are all short, complete sentences.

**Comment by S-LRaillard** [comment]
thanks! this has been fixed now.

**Comment by S-LRaillard** [comment]
@lb185064 could you please close this ticket? thanks!

**Comment by lb185064** [comment]
Thanks for fixing!
