### ISSUE TITLE
Example "Choose colors to use on webpages" wrongly uses bullets where numbered steps should be used.

### ISSUE THREAD

**Issue by hertzler-LJS** [MicrosoftDocs/microsoft-style-guide#344]
On the "Choose colors to use on webpages" example, step 2 should use numbered or lettered sub-steps to go to the Tools menu and Internet Options command.  The bullets wrongly make it look like these sub-steps are options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df353f5e-5a0a-293f-53cb-a87cb2296040
* Version Independent ID: 8440cb37-1384-c86a-a12c-7e9d6b924b46
* Content: [Describing alternative input methods - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods?source=recommendations)
* Content Source: [styleguide/procedures-instructions/describing-alternative-input-methods.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/describing-alternative-input-methods.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
This table has been reformatted in a different way. Please close this ticket.
