### ISSUE TITLE
Colon is rendered as &#58;

### ISSUE THREAD

**Issue by chanakavp** [MicrosoftDocs/microsoft-style-guide#350]
Colon is rendered as &#58.

![color MSG](https://user-images.githubusercontent.com/16893134/195546796-3288d8da-03b9-4f1f-b206-228f1bbbe498.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks! I've fixed this now.
