### ISSUE TITLE
Prepositions (IN or ON)

### ISSUE THREAD

**Issue by StYuSt** [MicrosoftDocs/microsoft-style-guide#355]
Dear Authors,

Could you please clarify which preposition we should use with PANE? In this article, you state that ON should be used when referring to the contents of a pane. However, there are no examples that make that statement clear.
By the way, in other articles of MSG and in MS Manual of Style 4th Edition, the word PANE is used with the preposition IN. E.g. In the **Apply Styles** pane, select **Modify**. https://learn.microsoft.com/en-us/style-guide/text-formatting/using-type/use-left-alignment

Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4ea46f9-489d-34ae-56e5-dc3c12978c98
* Version Independent ID: 09297cf6-ab53-1ab1-77a3-521c74cf6994
* Content: [pane - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/pane)
* Content Source: [styleguide/a-z-word-list-term-collections/p/pane.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/p/pane.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for this question - we will investigate and get back to you!

**Comment by S-LRaillard** [comment]
@StYuSt The current guidance is indeed to use "on" with pane. However, I can add this to the backlog of issues to be discussed by the editorial committee to see if changes are needed.
