### ISSUE TITLE
Main blue example doesn't follow written guidelines

### ISSUE THREAD

**Issue by LauraDSchneider** [MicrosoftDocs/microsoft-style-guide#356]
Hello, tech illustrator for this page!

Regrettably, the big blue sample diagram with running text used on this page (as viewed 11/21/22) is a **_very_** bad example that **does not follow the written standards on the page**. It has small, non-bold, white text on a solid-color background (always a "no-no"), and low-contrast other colors layered over other colors, including transparent, narrow, light yellow (weak color) lines over various shades of blue, low-contrast bullet points at the bottom in front of the text, and so on. 

The blue sample diagram is painful for me to view and understand (tech writer/illustrator with lens-corrected 20/20 vision). It would be hard or impossible for people with low-vision or color blindness to see and understand, and it would waste tons of ink/toner printing it out for people who wanted to do so (they still exist).

Please update this sample diagram to match the written advice about color contrast and accessibility!

Thank you,

Laura

Attached: Screenshot taken on Windows from the PDF file of the document, displayed at 100% size. Note that the white letters drop out even in the main, non-bold headings!

![MSFT Style Guide bug image](https://user-images.githubusercontent.com/66735779/203145953-990b5d31-a13d-4c35-be89-b3016fa13627.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 487e11e9-6e17-a1c7-a300-796b64b53b91
* Version Independent ID: 96af150e-f856-01c0-b65a-145f3f83c28c
* Content: [Illustrating network traffic flows - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/illustrating-network-traffic-flows)
* Content Source: [styleguide/procedures-instructions/illustrating-network-traffic-flows.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/illustrating-network-traffic-flows.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi and thanks for your feedback! We are aware that this illustration is out of date and are investigating how we can improve it to comply with Accessibility standards. We will circle back as we have more information.

**Comment by LauraDSchneider** [comment]
(oops, I clicked the wrong button)

**Comment by S-LRaillard** [comment]
Hi @LauraDSchneider , so sorry to drop the ball here. This topic has actually been retired entirely in the internal version of the guide, but somehow has not been deleted on this external version. I am working on that right now.

**Comment by LauraDSchneider** [comment]
Hi @S-LRaillard !

No worries on dropping the ball, it happens to all of us.

Just to clarify: are you saying that you're retiring the entire _topic of tech illustration_ from the Microsoft Style Guide?

If so, **_please_** tell me that Microsoft publishes (online, publicly available) tech illustration style guidelines somewhere that my team could reference! (Separate from marketing illustration guidelines, of course.)

As a tech writer/editor/illustrator/etc. with 30+ years across the broad tech comm field, I can't mentally separate the concepts of tech writing from tech illustration. Of course, simple to complex tech illustrations might be done by a tech illustrator in collaboration with a tech writer that does not have training, interest, proficiency, or just plain the software tools for doing the tech illustration themselves...

But, tech writing and tech illustration intermingle inseparably to convey complex topics to readers with different thinking styles, such as those with more visual brains. The words are always needed, of course (for alt or long_desc text, at minimum), but... sometimes _an illustration is just plain necessary_ to concepts best. They also help break up endless lines of text and procedures to help retain reader attention. And, they help _all_ readers grasp concepts by providing them from multiple perspectives. 

:-) Besides, who doesn't like a "book with pictures", especially in a complex installation or sys admin guide, system overview/concepts section, or troubleshooting decision trees?

Hoping for good news that this information was simply relocated elsewhere (fingers crossed)! 

And, thank you so much for removing the outdated, non-compliant, too-busy diagram! (There was much rejoicing.)

Cheers! 

--Laura

**Comment by S-LRaillard** [comment]
@LauraDSchneider hi again :) I meant that the topic "illustrating network traffic flows" was retired, as its original author felt it was no longer relevant. No other topics have been retired in the general domain of tech illustration. (see "procedures and instructions"). However, please note that the MWSG does not currently have a tech illustrator on hand, so this is largely outside of my scope of work for the moment.

**Comment by LauraDSchneider** [comment]
Hello again and good day, @S-LRaillard !  :-)   I'm SOOOO happy to hear this news! Wishing you a fantastic day **_and_** a tech illustrator added to your team in the very near future to flesh out and update those standards. They make all the difference to teams like mine who need concrete 3rd-party guidance on tech illustrations (as an internal employee, my word is simply an opinion, not "fact" unless I can show proof). And, honestly, I've read and referenced most of them, and **_nobody_** does style guides better than Microsoft: you all are simply the _**best**_.  Cheers!
