### ISSUE TITLE
Dynamic Configuration Assistant

### ISSUE THREAD

**Issue by keonglee1978** [MicrosoftDocs/microsoft-style-guide#359]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9ce006-d5ab-9155-9019-b329791bcfd2
* Version Independent ID: 3b8f6bb8-a499-0bad-d2d7-2e17af1afebd
* Content: [Special characters - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/special-characters)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/special-characters.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/term-collections/special-characters.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
please close this ticket @keonglee1978
