### ISSUE TITLE
Use numbered list instead of bulleted list for steps in the procedure

### ISSUE THREAD

**Issue by hertzler-LJS** [MicrosoftDocs/microsoft-style-guide#363]
In the table of **Mouse Actions** and **Keyboard Actions**, in the Internet Explorer example:

The current example shows  
- Click the **Tools** menu.
- Click **Internet Options**.

However, because this is a bulleted list, it looks like you have two alternatives for completing the procedure (which is not the case!)

The fix is to make it a numbered list instead of a bulleted list:

1. Click the **Tools** menu.
2. Click **Internet Options**.

Same for the example in the second column:

1. Select the **Tools** menu by pressing Alt+**T**.
2. Select **Internet Options** by pressing **O**.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df353f5e-5a0a-293f-53cb-a87cb2296040
* Version Independent ID: 8440cb37-1384-c86a-a12c-7e9d6b924b46
* Content: [Describing alternative input methods - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods?source=recommendations)
* Content Source: [styleguide/procedures-instructions/describing-alternative-input-methods.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/describing-alternative-input-methods.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
@hertzler-LJS Thanks for bringing this to our attention. It has now been fixed, please close this ticket, thanks!
