### ISSUE TITLE
Mistake in meta tag

### ISSUE THREAD

**Issue by ivancheban** [MicrosoftDocs/microsoft-style-guide#367]
<html>
<body>

<meta property="og:url" content="https://learn.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/emes" />
--
  | <meta property="og:description" content="Instructs to use an em dash (-) to set off a parenthetical phrase with more emphasis than parenthesis provide. Don't add spaces around **a** em dash." />

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 921295a2-2503-881a-e1a5-271f4a361053
* Version Independent ID: 536665af-b365-4b16-03b6-999826ac2185
* Content: [Em dashes - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/emes)
* Content Source: [styleguide/punctuation/dashes-hyphens/emes.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/punctuation/dashes-hyphens/emes.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
@ivancheban Thanks for flagging this! I've just fixed the meta text.
