### ISSUE TITLE
is it a typo? 

### ISSUE THREAD

**Issue by kind-envy** [MicrosoftDocs/microsoft-style-guide#368]
is it a typo? Recommended - Recommend

Replace this: The **Recommended** Charts command on the Insert tab recommends charts that are likely to represent your data well. Use the command when you want to visually present data, and you're not sure how to do it. 

With this: Create a chart that's just right for your data by using the **Recommend** Charts command on the Insert tab.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23388da6-bce7-7800-0335-38f82eedaf3c
* Version Independent ID: 7934337b-70be-7223-4e76-408f7086736a
* Content: [Top 10 tips for Microsoft style and voice - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/top-10-tips-style-voice)
* Content Source: [styleguide/top-10-tips-style-voice.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/sty
<img width="924" alt="Screenshot 2023-02-10 at 12 05 33 PM" src="https://user-images.githubusercontent.com/125017921/218063698-55865c50-f825-4c3e-9c5d-b915675bcfa6.png">
leguide/top-10-tips-style-voice.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by CBID2** [comment]
Is this issue still open?

**Comment by S-LRaillard** [comment]
@CBID2 Hi there, thanks for catching the typo. The correct name of the function is in fact "Recommended charts." https://support.microsoft.com/en-us/office/create-a-chart-with-recommended-charts-cd131b77-79c7-4537-a438-8db20cea84c0

This issue has been fixed.
