### ISSUE TITLE
Formatting Physical Addresses

### ISSUE THREAD

**Issue by paclife1** [MicrosoftDocs/microsoft-style-guide#371]
Can you please add information about physical addresses? We often have to provide where to mail something, for people who still use regular mail. 

P.O. Box vs PO Box?

123 N Main St vs 123 North Main Street 

123 N Main St, Madison, WI 54565. VS 123 N. Main St., Madison, WI, 54565.

Just some random examples but formatting of addresses and some of those common things like PO Box would be super helpful. 

Thank you!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97db8cca-0264-61ed-5571-3056564c2fca
* Version Independent ID: f70d33e8-e5cb-1abe-a27d-5fadeac2d197
* Content: [URLs and web addresses - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/urls-web-addresses)
* Content Source: [styleguide/urls-web-addresses.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/urls-web-addresses.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @paclife1, I would follow the USPS formatting of "PO Box" as seen here: https://www.usps.com/manage/po-boxes.htm (PO Box is also preferred by the Chicago Manual of Style).

For compass points, the MSWG aligns with the Chicago Manual of Style:

"Single-letter compass points accompanying a street name are normally followed by a period; two-letter compass points are not. Note that when used in an address, the abbreviations NE, NW, SE, and SW remain abbreviated even in running text (there is no comma before them when they follow a street name). The N in the third example is a street name and not a compass point.

1060 E. Prospect Ave. (or, in running text, 1060 East Prospect Avenue)
456 NW Lane St. (or, in running text, 456 NW Lane Street)
I stayed in a building on N Street SW, close to the city center.
A compass point that is the name (or part of the name) of a street or a place-name must never be abbreviated (e.g., South Ave., Northwest Hwy., South Shore Dr., West Bend, East Orange). "
