### ISSUE TITLE
Link to "OKR" doesn't work

### ISSUE THREAD

**Issue by yivanovarevizto** [MicrosoftDocs/microsoft-style-guide#375]
The link "[objectives and key results (OKR)](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/k/a-z-word-list-term-collections/o/objectives-and-key-results-(OKR))" doesn't work.

There is at least one more page where a link to OKR dpesn't work (sorry, forgot which one).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4c38df3-2bd7-bee8-5e94-bb838d7044ba
* Version Independent ID: a4c38df3-2bd7-bee8-5e94-bb838d7044ba
* Content: [key performance indicator (KPI) - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/k/key-performance-indicator-(KPI))
* Content Source: [styleguide/a-z-word-list-term-collections/k/key-performance-indicator-(KPI).md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/k/key-performance-indicator-(KPI).md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
@yivanovarevizto thanks for this - i will work on troubleshooting asap.
