### ISSUE TITLE
Question about the term "hibernating" on the loading screen after clicking Hibernate

### ISSUE THREAD

**Issue by wayneko** [MicrosoftDocs/microsoft-style-guide#376]
On a Windows computer, if you click Hibernate from the power option menu, the system goes into a loading screen showing "Hibernating". I doubt if this is correct:
- because when you see the loading screen, the computer has not yet entered hibernation. When I see "Hibernating", I would consider this computer is already hibernating right now, which is not true.
- In addition, if the process is described as "Hibernating", and how you describe the status when the computer is actually hibernating with one word? Please kindly answer my question. Thank you in advance!

See the picture here:
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFCYWp3LJrLGXOj5M-4F2cQRLzLax_gNKUojjQQleV_zO1lNvTk7Fn3fCUlXABosaxCIg&usqp=CAU

**Comment by S-LRaillard** [comment]
Hi @wayneko , this sounds like a question for the product team. I would recommend reaching out to the Windows team to see if they have more detailed information about this process (or if their terminologist does). Thanks!
