### ISSUE TITLE
What about Microsoft Excel?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [MicrosoftDocs/microsoft-style-guide#377]
Title case everywhere:

![image](https://user-images.githubusercontent.com/5159662/227010824-d3bfb27e-088f-4e9a-add6-3270dbec57a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72a047b5-771e-7a2a-d6ad-4038dd872397
* Version Independent ID: 9749bff4-8583-552b-284d-eee6d6340006
* Content: [Capitalization - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/capitalization)
* Content Source: [styleguide/capitalization.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/capitalization.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @wh1t3cAt1k , could you please clarify what your question is? I am not in charge of the designers at Excel, so I cannot control how they choose to capitalize feature and function names, unfortunately.
