### ISSUE TITLE
dialog box

### ISSUE THREAD

**Issue by srnilsen** [MicrosoftDocs/microsoft-style-guide#38]
Hi,  I think I found a small typo: "Don't use pop-up window or dialogue box", should read as "Don't use pop-up window for dialogue box."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6b1000-efe6-850a-ea21-5bc1c4c37607
* Version Independent ID: 971bbe67-6346-2e3f-3d88-d7f7677157b9
* Content: [dialog box, dialog, dialogue - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dialog-box-dialog-dialogue)
* Content Source: [styleguide/a-z-word-list-term-collections/d/dialog-box-dialog-dialogue.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/d/dialog-box-dialog-dialogue.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
That really is what we meant to say: Don't use *pop-up window* or *dialogue box.*
We're referring to the spelling of *dialog* versus *dialogue.*

Does that help?
