### ISSUE TITLE
Verb tense for reports

### ISSUE THREAD

**Issue by guyklages** [MicrosoftDocs/microsoft-style-guide#384]
While present tense is best 90% of the time, when is it ok to write in the past tense? For example, the 1st bullet is fine because it refers to past actions, right? Or is it better to write the 2nd bullet?
* This statement lists every transaction the consumer has made.
* This statement lists every transaction the consumer makes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e98fcd08-8edf-0a1d-2a62-6d827bc327b9
* Version Independent ID: d1ca993e-79e8-5373-44f4-c7390a736bfe
* Content: [Verbs - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/grammar/verbs)
* Content Source: [styleguide/grammar/verbs.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/grammar/verbs.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @guyklages, both sentences are fine, if slightly different in meaning. The first would be more appropriate when talking about a specific statement and specific customer - discussing a real list of purchases. The second would be more appropriate when talking generically about what function the statement performs (in general, it lists all the transactions a customer makes). Hope this helps!
