### ISSUE TITLE
Where are the templates and guidance for topic types?

### ISSUE THREAD

**Issue by chcomley** [MicrosoftDocs/microsoft-style-guide#389]
I can't find the Quickstart template. I don't see anything listed in the TOC about topic types. We should add that, unless I've missed it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0aae23d2-0a7b-4d83-23f3-34c419a8f230
* Version Independent ID: 4cc300c8-116f-d89e-973c-ac069169949c
* Content: [Procedures and instructions - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/)
* Content Source: [styleguide/procedures-instructions/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by DonGlover** [comment]
Sadly the templates are only available on the internal version of the style guide.

**Comment by S-LRaillard** [comment]
Hi @chcomley, Don above is correct. This is the external version of the style guide and it doesn't contain all of the same info.
