### ISSUE TITLE
Forcing "data" as singular

### ISSUE THREAD

**Issue by tfjield** [MicrosoftDocs/microsoft-style-guide#393]
MS grammar checking is forcing the use of "data" as a singular noun. The use of "data" as singular or plural is controversial (as is using the singular "datum" instead of the singular "data"), and therefore I believe there should be an option based on the writer's preference.  Rather than flagging all use of "data" as plural as potentially incorrect and requiring manually ignoring the instance or turning off the rule, it would be better to allow the option to treat it as singular or plural.  Much like the option to use or not use the Oxford comma.

While this is a style guide and not specific to the grammar checker, the use of "data" as plural should also be an option here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb7e780-6066-1cea-50df-569726bb188a
* Version Independent ID: 48366110-7f4a-f705-9c71-fcfaf4fab549
* Content: [data, datum - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/data-datum)
* Content Source: [styleguide/a-z-word-list-term-collections/d/data-datum.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/d/data-datum.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by tfjield** [comment]
Thank you for your response, and I understand your position.  However, this is also from the American Heritage dictionary, same entry, indicating that "data" is a plural noun used with a singular **or** plural verb:

> da·ta  (dā'tə, dăt'ə, dä'tə)
> pl.n. (used with a sing. or pl. verb)
> 1. Facts that can be analyzed or used in an effort to gain knowledge or make decisions; information.
> 2. Statistics or other information represented in a form suitable for processing by computer.
> 3. Plural of [datum]

And:

> **Usage Note:** The word data is the plural of Latin datum, "something given." In English, most notably in scientific usage, this plural usage is still common, as in this example: "Eventually, his data suggest, a tumor's ... alterations give rise to mutant cells" (Janet Raloff). 

Many people use MS products for scientific writing and adhere to this standard, and grammar checker flags this usage as potentially incorrect.  And I would suggest that many people who use "data" as plural in their scientific writing also use it as plural in their general communication.  While us scientists and engineers are probably not the majority, we comprise (and will continue to comprise, I hope) a significant segment of the population using MS products.

For these reasons, I think it should be an _option_ to use it as singular _or_ plural.

**Comment by S-LRaillard** [comment]
Hi @tfjield I totally understand your point. I think, however, the main issue you are having is with the MS grammar checker, which is NOT actually controlled by the same team as the MWSG. We take a position in the MWSG based on what is going to work for the majority of communications, but I'm not entirely sure how the grammar checker decides what its rules are. I can see if the editorial committee wants to add a caveat to the MWSG topic, but that's unlikely to change anything about your current situation, sorry!

**Comment by tfjield** [comment]
Thank you, @S-LRaillard!  I understand, of course.  Yes, I doubt it will change anything, but if there is at least a caveat, maybe it will help someone else realize that singular usage isn't a hard-and-fast rule.  I appreciate your time!
