### ISSUE TITLE
Half Right

### ISSUE THREAD

**Issue by scratchtasia** [MicrosoftDocs/microsoft-style-guide#394]
A correction was made to the second sentence after my previous comment about the preposition to be used for panes (_on_ rather than _in_), but it is still only half-correct. The last part of the sentence should be "_on_ another pane."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4ea46f9-489d-34ae-56e5-dc3c12978c98
* Version Independent ID: 09297cf6-ab53-1ab1-77a3-521c74cf6994
* Content: [pane - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/pane#feedback)
* Content Source: [styleguide/a-z-word-list-term-collections/p/pane.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/p/pane.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
@scratchtasia Will incorporate asap, thanks.
