### ISSUE TITLE
popup no longer requires a hyphen

### ISSUE THREAD

**Issue by writerMaia** [MicrosoftDocs/microsoft-style-guide#398]
Recommend changing "pop-up" to "popup" when used as an adjective. 
Like this: _popup window_
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff12cba-b5ba-2218-7c5e-f44d8ea1d3ba
* Version Independent ID: b5bccc7e-8a28-9eee-d291-bb07d135d5c3
* Content: [pop-up - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/pop-up)
* Content Source: [styleguide/a-z-word-list-term-collections/p/pop-up.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/p/pop-up.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @writerMaia , thanks for the feedback. There has not been a change at Microsoft in the hyphenation of "pop-up + noun" as we align with the American Heritage Dictionary in most cases. Language is constantly evolving, however, so this may change in the future!
