### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by JohnDocsMarks** [MicrosoftDocs/microsoft-style-guide#399]
[I think this example is wrong. The subject of the sentence is "games". It should be "A variety of games are available from Microsoft Store."]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e98fcd08-8edf-0a1d-2a62-6d827bc327b9
* Version Independent ID: d1ca993e-79e8-5373-44f4-c7390a736bfe
* Content: [Verbs - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/grammar/verbs)
* Content Source: [styleguide/grammar/verbs.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/grammar/verbs.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by Jay-o-Way** [comment]
"variety" takes precedence and is singular

**Comment by S-LRaillard** [comment]
Hi @JohnDocsMarks, "Variety" is actually the singular subject of the verb, but I see how this could be confusing at first glance. We'll look into finding a clearer example.

**Comment by Jay-o-Way** [comment]
Looks like we were wrong https://forum.thefreedictionary.com/postst5937_a-variety-of--singular-or-plural.aspx
