### ISSUE TITLE
Emphasis

### ISSUE THREAD

**Issue by jay-saldanha** [MicrosoftDocs/microsoft-style-guide#4]
In the example for the element Emphasis no word is in italics. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28c9871-f3a6-2dc1-1494-93f981f50238
* Version Independent ID: 8e95f7bc-399a-7648-36bd-8dd7dc90f347
* Content: [Formatting common text elements - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/text-formatting/formatting-common-text-elements#feedback)
* Content Source: [styleguide/text-formatting/formatting-common-text-elements.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/text-formatting/formatting-common-text-elements.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Oh, yes, that's an error. The word "never" is supposed to be italic. We'll get that in the queue to be fixed. Thanks for letting us know!

**Comment by jay-saldanha** [comment]
You're welcome!
