### ISSUE TITLE
Phone Numbers

### ISSUE THREAD

**Issue by bridgetnaomi** [MicrosoftDocs/microsoft-style-guide#40]
How do you recommend formatting phone numbers, both for the United States and international?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f47e95a-2a10-bf53-6518-419ecb8ac3d3
* Version Independent ID: e42e5d8a-dcf2-872e-2786-c9ddde6e47d5
* Content: [Numbers - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/numbers)
* Content Source: [styleguide/numbers.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/numbers.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Unfortunately, the Microsoft Writing Style Guide doesn’t yet have guidelines for phone number formats, though it’s something we might add in the future.
