### ISSUE TITLE
Incorrect link in PDF

### ISSUE THREAD

**Issue by CRZ** [MicrosoftDocs/microsoft-style-guide#401]
Greetings,

In the "What's New" section of the PDF, clicking on the "Bluetooth" link doesn't take you to the Bluetooth section of the PDF as expected, but instead back to learn.microsoft.com.

Thanks,
CRZ

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @CRZ this was fixed a while ago - sorry for only responding to you now!
