### ISSUE TITLE
What happened to #avoid-negations?

### ISSUE THREAD

**Issue by Surname-Surname** [MicrosoftDocs/microsoft-style-guide#403]
When were the requirements to avoid negations and negative forms removed and for which reasons?
https://learn.microsoft.com/en-us/style-guide/grammar/negatives
https://learn.microsoft.com/en-us/style-guide/top-10-tips-for-microsoft-style-and-voice#avoid-negatives

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @Surname-Surname , it looks like this happened before 2018, because that's how far my records date and I don't see that change happening between now and then. Sorry to not have more clarity!
