### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Loriho23** [MicrosoftDocs/microsoft-style-guide#408]
Oh, Microsoft. You're usually always so perfect! 
![image](https://github.com/MicrosoftDocs/microsoft-style-guide/assets/142049963/994c5d3c-9f13-499d-8a04-2c86539e3264)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for the eagle eyes @Loriho23 ! I'll catch that now.
