### ISSUE TITLE
Use blade to refer to a pane in the Azure portal. Avoid talking about blades.

### ISSUE THREAD

**Issue by dougscc** [MicrosoftDocs/microsoft-style-guide#409]
[Enter feedback here]
> Use blade to refer to a pane in the Azure portal. Avoid talking about blades.

Perhaps referring to a "blade" as a "slidey-slidey-lost-my-place" would make the concept more clear to the end user? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0aac9bd1-0fa5-2e6a-52db-6aafee9930de
* Version Independent ID: c3d39f0c-d12b-f67f-b8fa-fe041f76db49
* Content: [blade - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blade)
* Content Source: [styleguide/a-z-word-list-term-collections/b/blade.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/b/blade.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for the feedback, @dougscc . This has been reworded to be clearer: Avoid talking about UI elements and instead try to discuss what the customer needs to do. If you have to refer to a pane in the Azure portal, use blade.
