### ISSUE TITLE
why browse over navigate? =)

### ISSUE THREAD

**Issue by NHamilton01** [MicrosoftDocs/microsoft-style-guide#411]
Hi! I don't have any feedback, but my team is curious why you recommend browse over navigate. Thanks for any info you can provide!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d781cad-e670-1161-966f-e7cd5f9e4ea1
* Version Independent ID: 6dd87ed3-c055-b86d-ef0d-59564ae602fd
* Content: [navigate - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/n/navigate)
* Content Source: [styleguide/a-z-word-list-term-collections/n/navigate.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/n/navigate.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by LauraDSchneider** [comment]
My $0.02: I prefer "browse" over "navigate" for readability reasons.
Browse has
- one syllable, not three.
- fewer possible meanings, so people with low literacy (the majority worldwide) are more likely to pick the correct meaning.

Also, if you didn't know the word "navigate" and looked it up in a dictionary, it could lead to confusion (boat and aircraft navigation, physical movement of objects with respect to each other or a point in ground or water...).

Navigate is just "messier" than browse. If that makes sense. LOL :-)

**Comment by S-LRaillard** [comment]
Hi there - @LauraDSchneider got here before me with excellent reasoning :)
