### ISSUE TITLE
comma+and then is 1 and too many

### ISSUE THREAD

**Issue by writerMaia** [MicrosoftDocs/microsoft-style-guide#414]
You can remove a word from this phrase: ...xxx, and then...
Recommend shortening to: ...xxx, then...
Note that the comma means "and"
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df353f5e-5a0a-293f-53cb-a87cb2296040
* Version Independent ID: 8440cb37-1384-c86a-a12c-7e9d6b924b46
* Content: [Describing alternative input methods - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods)
* Content Source: [styleguide/procedures-instructions/describing-alternative-input-methods.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/procedures-instructions/describing-alternative-input-methods.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for the suggestion, @writerMaia! This has been implemented.
