### ISSUE TITLE
h

### ISSUE THREAD

**Issue by zeinabkamel** [MicrosoftDocs/microsoft-style-guide#417]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28284335-e258-1c98-9017-65c35b8fcb48
* Version Independent ID: 9e40fdb4-7a18-26cb-2923-567f273686d8
* Content: [service-oriented architecture (SOA) - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/service-oriented-architecture-soa)
* Content Source: [styleguide/a-z-word-list-term-collections/s/service-oriented-architecture-soa.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/s/service-oriented-architecture-soa.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @zeinabkamel could you elaborate on your issue? Thanks!
