### ISSUE TITLE
You either meant a plural word or to produce this singular word with an article

### ISSUE THREAD

**Issue by CLiebendorfer** [MicrosoftDocs/microsoft-style-guide#418]
"Don’t use colon when introducing lists of radio buttons or checkboxes." I think you mean "colons" or "a colon."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 940e15a9-149b-04fc-4cab-186a48bbe874
* Version Independent ID: 779b9d15-f811-2da7-ae4a-62874ba79446
* Content: [Colons - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/punctuation/colons)
* Content Source: [styleguide/punctuation/colons.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/punctuation/colons.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @CLiebendorfer  thanks for the typo spotting! We'll fix asap.
