### ISSUE TITLE
Please add guidance here about which preposition to use with UI elements

### ISSUE THREAD

**Issue by rhanajoy** [MicrosoftDocs/microsoft-style-guide#428]
As an editor of Microsoft product articles, I would LOVE to have a list of UI elements and the correct preposition to use with them, all on one page, and this seems like the most logical page. For instance, I know that I select something "on the ribbon," but do I do something "on a tab" or "in a tab," "on the page" or "in the page"? Do I select something "in the list" or "from the list"? And on and on and on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e98e42eb-e358-ac20-3d03-797f01106e89
* Version Independent ID: c8035ad5-f27a-c286-7c75-7f7be79ce7ad
* Content: [Prepositions - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/grammar/prepositions)
* Content Source: [styleguide/grammar/prepositions.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/grammar/prepositions.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Thanks for the feedback, @rhanajoy ! This is definitely a big and thorny issue that we are working on. We'll add your comments to our discussion.
