### ISSUE TITLE
Link to join the Microsoft Style Guide updates email distribution group broken

### ISSUE THREAD

**Issue by brittanyshands** [MicrosoftDocs/microsoft-style-guide#429]
[Hello! I attempted to join the email distro about style guide updates, but the link appears broken. Included screenshots of errors.
<img width="714" alt="2024-01-08 10_27_52-Microsoft Writing Style Guide" src="https://github.com/MicrosoftDocs/microsoft-style-guide/assets/105938047/0b9e2086-3af4-4a74-8428-51613cc35046">
<img width="614" alt="2024-01-08 10_31_02-idwebelements" src="https://github.com/MicrosoftDocs/microsoft-style-guide/assets/105938047/60cf5e7a-f130-459a-8892-71012dd4b1de">
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi @brittanyshands, this is very strange. You appear to be referring to an old page that is not on my repo? This is the welcome page that SHOULD be displaying for you, and which is live on the github public repo for me: https://learn.microsoft.com/en-us/style-guide/welcome/
The screenshot you are including does not exist on the external style guide, only on the Microsoft-only internal guide. Can you please let me know how you accessed this?

**Comment by brittanyshands** [comment]
I am so sorry! I don't know why my GitHub is connected to my personal email because I've only ever used it for work! My v- is v-bshands@microsoft.com

**Comment by brittanyshands** [comment]
Ah, sorry for the confusion!

**Comment by S-LRaillard** [comment]
Hi @brittanyshands  this issue has been fixed with a new link and the deletion of groups that are no longer active. Thanks for raising the issue!

**Comment by brittanyshands** [comment]
I have a follow-up question: a few of my coworkers are on their v- break.
Are we able to add external emails to the distro list?

**Comment by S-LRaillard** [comment]
Hi Brittany,
Unfortunately, it’s not possible to add non-Microsoft accounts to the DG as access to the internal style guide (again, not the external one you are messaging me from) is considered confidential.
They are welcome however to check the “What’s New” section in the external style guide, which will reflect the vast majority of the changes made internally.

Best,
SL
