### ISSUE TITLE
View tab

### ISSUE THREAD

**Issue by ivancheban** [MicrosoftDocs/microsoft-style-guide#47]
Dear Microsoft, in the "To switch between Normal, Outline, and Slide Sorter views, use the buttons on the View tab." the word "tab." should not be bold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ad46ad-342d-da22-47a6-504ce7a06a95
* Version Independent ID: 3f8c7233-e250-e7f7-faff-c90b91ff03c7
* Content: [Describing interactions with UI - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)
* Content Source: [styleguide/procedures-instructions/describing-interactions-with-ui.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/procedures-instructions/describing-interactions-with-ui.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hello,
Thanks for letting us know! This will be fixed shortly.
