### ISSUE TITLE
Numerals in a group

### ISSUE THREAD

**Issue by DineshSinghK** [MicrosoftDocs/microsoft-style-guide#48]
The rule states the following:
"Be consistent within categories of information. If one number in a category requires a numeral, use numerals for all the numbers in that category."

The example seems to contradict:
"The team has two product managers, 12 designers, six writers, and 16 developers."
Shouldn't this be:
"The team has 2 product managers, 12 designer, 6 writers, and 16 developers."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f47e95a-2a10-bf53-6518-419ecb8ac3d3
* Version Independent ID: e42e5d8a-dcf2-872e-2786-c9ddde6e47d5
* Content: [Numbers - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/numbers)
* Content Source: [styleguide/numbers.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/numbers.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
We've updated the guideline and the examples for it, so hopefully this is clearer.
