### ISSUE TITLE
"up to" should be "up to"

### ISSUE THREAD

**Issue by pivic** [MicrosoftDocs/microsoft-style-guide#49]
Two words have erroneously been written as one; please change "upto" to "up to".

**Comment by camind** [comment]
Hi,
The details for this issue aren't showing up, and I'm having trouble finding what topic your note pertains to. Could you let me know the name of the topic where you found this typo? Many thanks. Catherine

**Comment by pivic** [comment]
Hi, @camind! I'm sorry, but I cannot find the part where it was written; perhaps I used GitHub erroneously, and I merely commented in the topic where I found fault. Thanks for letting me know. /Nik

**Comment by camind** [comment]
No worries. If you find it again, let us know. Thanks!
