### ISSUE TITLE
Missing format used

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/microsoft-style-guide#5]
It would be great if the format on how acronyms should be used was also added. We first spell out and then add the acronym in parentheses. I wanted to send this topic to someone internally on how to do acronyms (given they were doing the opposite) and I've noticed it didn't have this specific information on the format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d30bb26-5486-e2d9-851b-47ceeb6d07b5
* Version Independent ID: 295d184a-a254-acea-6185-b14346fb0634
* Content: [Acronyms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/acronyms)
* Content Source: [styleguide/acronyms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/acronyms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
hi Maira, 
This information is in the subsection [If you have to use an acronym, also spell out the term for clarity](https://docs.microsoft.com/en-us/style-guide/acronyms#if-you-have-to-use-an-acronym-also-spell-out-the-term-for-clarity), which says, "In general, include the acronym in parentheses following the spelled-out term. On subsequent mentions in the same topic, page, or screen, you can use the acronym without spelling it out." 

And that pattern is demonstrated in the example for that subsection and in several other examples in the topic.

**Comment by mairaw** [comment]
Duh, you're right @camind. Somehow I missed that!

**Comment by camind** [comment]
:)
