### ISSUE TITLE
Update MSDN and TechNet reference

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/microsoft-style-guide#50]
This page references "MSDN or TechNet libraries." Since those no longer exist, it would be good to update to "Microsoft Docs" or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 509c701d-60bd-0e53-7118-7fd76a4717ca
* Version Independent ID: 4d3d6495-ace0-b7f2-a897-6dab86f56dde
* Content: [Scannable content - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/scannable-content/)
* Content Source: [styleguide/scannable-content/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/scannable-content/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
@tomresing this has been completed a while ago :)

**Comment by tomresing** [comment]
@S-LRaillard Maybe I'm looking in the wrong place. I still see the references to MSDN and TechNet on this page: https://learn.microsoft.com/en-us/style-guide/scannable-content/

**Comment by S-LRaillard** [comment]
@tomresing you are absolutely right! I missed one instance in the external guide because I was focused on the internal version :) fixing now!

**Comment by tomresing** [comment]
Glad this GitHub issue helped. I hope we can use them more in the future!
