### ISSUE TITLE
"on a local machine" usage

### ISSUE THREAD

**Issue by ahungund** [MicrosoftDocs/microsoft-style-guide#53]
Hi,

I see that "on a local machine" is a widely used phrase across the industry (even in Microsoft documentation). Could you add some usage tips here as to when it is acceptable? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05123b7d-5b85-9305-ee29-5a1ab9d6a2c0
* Version Independent ID: 97a0397f-37bc-3d9a-237e-e8fb556e7b4c
* Content: [machine - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/machine)
* Content Source: [styleguide/a-z-word-list-term-collections/m/machine.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/m/machine.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Thanks for contacting us. I'm not sure I understand your request.
What sort of usage information are you looking for or would recommend? 
The style guide gives usage direction when a term has a variant (for example, capitalization, hyphenation, or spelling). Or when Microsoft style prefers one term over another. 

For "on a local machine," what information does a writer need to know to use the phrase correctly or appropriately?
Thanks! Catherine
