### ISSUE TITLE
Add username and password to the Word list

### ISSUE THREAD

**Issue by a-akimov** [MicrosoftDocs/microsoft-style-guide#54]
Hey, we noticed that you are using "username" (vs. "user name") and "password" (vs "pass") in your style guide, but they are not present in a word list. Can you please add them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183f3218-c033-2374-5b32-8493e889516a
* Version Independent ID: 924752c0-d179-28c5-7c73-65c7ba036b71
* Content: [Security terms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/security-terms)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/security-terms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/term-collections/security-terms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Thanks for contacting us. We've omitted "username" and "password" intentionally. Microsoft's preferred dictionary is [American Heritage](https://ahdictionary.com/), and both of those words are in *American Heritage* as one word. To help us remain aligned with the latest entries in *American Heritage* and to avoid unnecessary work, we typically don't include terms in the *Microsoft Writing Style Guide* if they're listed in the dictionary.

So if you don't see the term you're looking for in the Microsoft Writing Style Guide, check [American Heritage Dictionary](https://ahdictionary.com/). And if *American Heritage* lists alternative spellings for a word, Microsoft style is to use the first one.

Hope that helps--
Catherine
