### ISSUE TITLE
Select or click a button

### ISSUE THREAD

**Issue by v-alexam** [MicrosoftDocs/microsoft-style-guide#56]
Shouldn't a button be clicked? Are we discussing a particular kind of button that's indeed selected? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c838cc4-2c32-b9d2-875d-8695b8a4edc4
* Version Independent ID: 74e22e7f-b91f-4874-d42c-ce13912b77d9
* Content: [button - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/button#feedback)
* Content Source: [styleguide/a-z-word-list-term-collections/b/button.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/b/button.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
It's a fair question, but Microsoft style purposefully says to use "select" as the verb for user interaction with buttons. 
If you're using a mouse, you _click_ a button, but if you're using a tablet or phone, you might _tap_ it. If you're using an assistive device, you might use some other action.

To support customers of all abilities and the many different ways that people use their devices, we document all the ways that customers can interact with the UI. Most of the time, this means writing the procedure in such a way that it uses input-neutral verbs ("select"). And then the documentation also includes an article that explains how to interact with the product using each available input method. In an article or procedure that's _specifically_ about mouse procedures, it would be appropriate to use "click."

You can find more info in [Describing alternative input methods](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods).
Thanks!
Catherine
