### ISSUE TITLE
More advices for writing effective step-by-step instructions

### ISSUE THREAD

**Issue by ClementFlipo** [MicrosoftDocs/microsoft-style-guide#58]
The main issue about writing step-by-step instructions is that usually this process is incredibly time- and resource consuming. To kill two birds with one stone and get rid of voluminous technical documentation work, I have written this article who combine the best practices for writing effective work instructions that I have learned over years:
https://dokit.io/best-practices-for-writing-effective-work-instructions/
I hope this help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b5e3aa-271d-e55e-5c7c-fd31ec3ae360
* Version Independent ID: 18c8323f-fa16-669e-2d58-f959b8b772d7
* Content: [Writing step-by-step instructions - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/writing-step-by-step-instructions#feedback)
* Content Source: [styleguide/procedures-instructions/writing-step-by-step-instructions.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/procedures-instructions/writing-step-by-step-instructions.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Thanks for your post, we'll check it out.
