### ISSUE TITLE
Pronouns & Gender fallback example #2 uses exclusionary language

### ISSUE THREAD

**Issue by F-Jennings** [MicrosoftDocs/microsoft-style-guide#59]
If one [bias-free communication](https://docs.microsoft.com/en-us/style-guide/bias-free-communication) goal is for all communications to be `inclusive and diverse`, the [Pronouns & Gender section](https://docs.microsoft.com/en-us/style-guide/grammar/nouns-pronouns#pronouns-and-gender) does not currently meet that goal. Its example # 2 for when a pronoun can't be written around:
> Use _he or she_.

uses exclusive language that implies a gender binary. Similarly, # 3 isn't exclusive in the same way but could be clearer that "he" and "she" are not the only pronouns that people use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b09ead4-ad5c-0b95-1705-94acb5f80774
* Version Independent ID: 94773f5e-7f0c-b331-db01-76cc1483c9b1
* Content: [Nouns and pronouns - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/grammar/nouns-pronouns)
* Content Source: [styleguide/grammar/nouns-pronouns.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/grammar/nouns-pronouns.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Thanks very much for your comment. The Microsoft Editorial Board is looking at our guidelines and what modifications should be made to address gender-neutral language. We appreciate your feedback.
Regards, Catherine

**Comment by F-Jennings** [comment]
Thanks Catherine! I'll keep an eye on the page for updates.

**Comment by F-Jennings** [comment]
It looks like this got updated [the other day](https://github.com/MicrosoftDocs/microsoft-style-guide/commit/83cc25d4395b0eadf7c990f4fc219ea1e4085a64#diff-d3895a3fd9e334876290b04a6384a37d), just wanted to say thanks very much!
