### ISSUE TITLE
Ms.

### ISSUE THREAD

**Issue by KA-1** [MicrosoftDocs/microsoft-style-guide#6]
The sentence "Microsoft style is sentence-style capitalization." is grammatically incorrect.
This is obvious if you remove the adjective, so the sentence reads "Microsoft style is capitalization."
A grammatically-correct version of this sentence would be "Microsoft style uses sentence-style capitalization."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a047b5-771e-7a2a-d6ad-4038dd872397
* Version Independent ID: 9749bff4-8583-552b-284d-eee6d6340006
* Content: [Capitalization - Microsoft Style Guide](https://docs.microsoft.com/en-ca/style-guide/capitalization)
* Content Source: [styleguide/capitalization.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/capitalization.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Thanks for pointing this out. This is a bit of jargon that sneaked into our guidelines …. We'll put this on our list of revisions to make.

**Comment by KA-1** [comment]
☺
