### ISSUE TITLE
Change example to say later in this article

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/microsoft-style-guide#63]
The documentation team can no longer use the word topic. It's considered legacy and we use article instead. I think it should be good to update the example here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efeb973c-85ab-50c0-be11-3ead2dc7f411
* Version Independent ID: 7f805eac-744e-2121-a062-57f9750762fc
* Content: [below - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/below)
* Content Source: [styleguide/a-z-word-list-term-collections/b/below.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/b/below.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi Maira,
My team is looking for more details and background. I've sent you email so we can follow up offline. 
thanks,
Catherine
