### ISSUE TITLE
update links

### ISSUE THREAD

**Issue by VerenaHeld** [MicrosoftDocs/microsoft-style-guide#64]
Some links won't work ("Virtual PC Guy’s blog" or "5 easy and powerful Excel features you may not know about").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e18760a-7e18-d71b-3d45-3be5f6b366c7
* Version Independent ID: 275cab7d-5037-029b-7b3f-5d2a2f6fc107
* Content: [Content planning - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/content-planning#feedback)
* Content Source: [styleguide/content-planning.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/content-planning.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by rmlos** [comment]
Also, links outdated in the section "Learn or increase knowledge and skills related to a product, service, technology, or business concept".

**Comment by camind** [comment]
Hi,
Thanks for letting us know. We have an update planned for this article, with updated links.
If you have any suggestions--any Microsoft content that you think illustrates the guidelines in this article--we'd love to hear them!
