### ISSUE TITLE
Hardcoding?

### ISSUE THREAD

**Issue by PatrickHammond66** [MicrosoftDocs/microsoft-style-guide#65]
Hardcoding, hard-coding or hard coding?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a15f983-3525-9dc2-e875-6e1b00e29fae
* Version Independent ID: 83cc9e57-04be-ea45-557f-b81151eb2c5c
* Content: [hard-coded - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/h/hard-coded)
* Content Source: [styleguide/a-z-word-list-term-collections/h/hard-coded.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/h/hard-coded.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
It would be "hard-coding." We updated the article to be [hard-code, hard-coded, hard-coding](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/h/hard-code-hard-coded-hard-coding).

**Comment by PatrickHammond66** [comment]
Thanks!!

**Comment by PatrickHammond66** [comment]
Thanks!
