### ISSUE TITLE
Numerals vs. words example

### ISSUE THREAD

**Issue by ahungund** [MicrosoftDocs/microsoft-style-guide#69]
In the bullet point "Be consistent within categories of information. If one number in a category requires a numeral, use numerals for all the numbers in that category," the following example is not very convincing:
"The team has two product managers, 12 designers, six writers, and 16 developers."
Chicago Manual of Style, 9.7 (Consistency and flexibility), doesn't give any such examples. 
If we are putting product managers and writers in one category, and designers and developers in another category, the distinction is so feeble that the logic is almost lost, and the sentence seems just inconsistent. 
Please consider replacing this example with a better one where the two categories are distinct. Right now, it just looks inconsistent and wrong.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f47e95a-2a10-bf53-6518-419ecb8ac3d3
* Version Independent ID: e42e5d8a-dcf2-872e-2786-c9ddde6e47d5
* Content: [Numbers - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/numbers#feedback)
* Content Source: [styleguide/numbers.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/numbers.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
We've updated the guideline and the examples for it, so hopefully this is clearer.
