### ISSUE TITLE
Consciously and purposely undo popular partialities

### ISSUE THREAD

**Issue by ArcPam** [MicrosoftDocs/microsoft-style-guide#70]
Still wondering how best to remove references to such a inhuman mark on history and current practices, only to be used in a professional meeting between billion-dollar corporations. Find a better synonym to clarify your concept.

"When you need to clarify the concept, it's OK to reference the use of slave as an adjective by saying also known as the slave server. It's OK to use master server and slave server as synonyms in keyword lists."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee040a8a-cdb7-025a-1b40-0f6223ec369b
* Version Independent ID: 773f1c83-b79a-783d-b584-3eff0c9c0173
* Content: [master/slave, master/subordinate - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/master-slave-master-subordinate#feedback)
* Content Source: [styleguide/a-z-word-list-term-collections/m/master-slave-master-subordinate.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/m/master-slave-master-subordinate.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Actually, Microsoft style is very clear about not using the term. The very first sentence of the article says, very clearly, "Don't use *master/slave.*"

And it's lamentable, but many developers still use that term, and content creators need to make sure those people find their technical content. So, sometimes writers may need to include the reference--but always with the preferred term presented *as the preferred term,* and used throughout the rest of the article. In this way, the writer can introduce the less inhumane term to those folks who are unacquainted with it. We place a lot of trust in writers and believe they'll show good judgment in applying the guideline.
