### ISSUE TITLE
No more UI chapter?

### ISSUE THREAD

**Issue by caitlinandrews** [MicrosoftDocs/microsoft-style-guide#73]
Is there no UI chapter or am I just not seeing it? I thought it was really useful for going over microsoft UI terminology especially since terms like tiles or Start screen are used in examples throughout the style guide. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Thanks for reaching out to us--this is very useful feedback.
You're right. The current Microsoft Writing Style Guide doesn't have a chapter dedicated to UI terminology. This is something we're working on. The goal is to have updated UI design/terminology guidelines in the style guide in the future.
Regards, Catherine

**Comment by sdwheeler** [comment]
There is some information at https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui
