### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by Ashbringer7077** [MicrosoftDocs/microsoft-style-guide#76]
This is Brillant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c646d8c7-4829-2567-c5c7-a9f526f7a569
* Version Independent ID: 8ef7d393-8cdb-42b8-6db4-31633fdad102
* Content: [Touch and pen interaction terms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/touch-pen-interaction-terms)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/touch-pen-interaction-terms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/term-collections/touch-pen-interaction-terms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hey, thanks!
(I hope you're not being sarcastic ;)
