### ISSUE TITLE
Include the correct format to write web application into the style guide

### ISSUE THREAD

**Issue by SSParamee** [MicrosoftDocs/microsoft-style-guide#78]
[Enter feedback here]
Enter the correct format of writing web application (web-app, webapp, web application etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e0cd5f-f5a5-4896-a9c6-c784a3d5f030
* Version Independent ID: cc261803-9166-fbcc-c399-782eec52c736
* Content: [web, World Wide Web, WWW - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www)
* Content Source: [styleguide/a-z-word-list-term-collections/w/web-world-wide-web-www.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/w/web-world-wide-web-www.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Good point. The preferred form is two words, and "web app" is preferred to "web application." The article is updated to reflect this. Thanks for contacting us, 
Catherine

**Comment by SSParamee** [comment]
Cool, Thanks. Closing this issue as this is resolved.
