### ISSUE TITLE
Mention about using the word 'sign up'

### ISSUE THREAD

**Issue by SSParamee** [MicrosoftDocs/microsoft-style-guide#79]
It would be better to describe the usage of _Sign up_, similar to sign in. Already, _Log in_ and _Sign in_ are mentioned. 

It would be better to have samples where exactly _sign up_, _sign in_ and _log in_ must use when writing.

According to my understanding, they are as follows:

- Sign up: When a user is registering for a particular service

- Sign in: When a user is entering the username and password in a UI console

- Log in: When a user is entering the username and password to a server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72348d28-62c9-91b5-4dfa-b5e74c4c7c8e
* Version Independent ID: 89199b13-a047-8f74-364d-8e685a1e53c8
* Content: [sign in, sign out - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/sign-in-sign-out)
* Content Source: [styleguide/a-z-word-list-term-collections/s/sign-in-sign-out.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/s/sign-in-sign-out.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
Thanks for your feedback. The need for "sign up" guidelines is a known issue and something that's being considered for future updates.
However, Microsoft style recommends not using "log on" (or other, similar "log" terms) at all, unless it appears in the UI and you're writing procedures that reference the UI. The style recommends "sign in" and "sign out" instead. See [sign in, sign out](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/sign-in-sign-out).
