### ISSUE TITLE
Why is they'll ambiguous?

### ISSUE THREAD

**Issue by TWMadhavi** [MicrosoftDocs/microsoft-style-guide#80]
Hello MS, why do you point out "they'll" as an ambiguous contraction while "you'll" and "we'll" are used in this guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a01a5f-ceaf-9245-d6dd-ba9571c674c4
* Version Independent ID: 8c06242d-0683-0fb7-4da9-fde8aef14118
* Content: [Use contractions - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions#feedback)
* Content Source: [styleguide/word-choice/use-contractions.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/word-choice/use-contractions.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Good question--we've updated this to say that "ambiguous and awkward contractions" should be avoided. That is, it's not just ones that might be ambiguous but also ones that just sound or read weirdly. And we changed the example from "they'll" to "they'd." Thanks.
