### ISSUE TITLE
Include the correct way to write 'web interface' 

### ISSUE THREAD

**Issue by SSParamee** [MicrosoftDocs/microsoft-style-guide#83]
[Enter feedback here]
Shall we add the correct way to write 'web interface' into the style guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e0cd5f-f5a5-4896-a9c6-c784a3d5f030
* Version Independent ID: cc261803-9166-fbcc-c399-782eec52c736
* Content: [web, World Wide Web, WWW - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www)
* Content Source: [styleguide/a-z-word-list-term-collections/w/web-world-wide-web-www.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/w/web-world-wide-web-www.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi,
What would you need to know about the term? The topic doesn't list it as one of the terms that's now spelled as one word (like _website_), so the usual English grammar rules would apply, and it would be two words. Is there anything else confusing or ambiguous about the term that needs to be clarified? Thanks!

**Comment by SSParamee** [comment]
Yes, this answers my inquiry. Thanks for getting back.
