### ISSUE TITLE
How to writer end user?

### ISSUE THREAD

**Issue by SSParamee** [MicrosoftDocs/microsoft-style-guide#85]
There are conventions to write end user as;

- end user

- end-user

- enduser

Which of these is the standard to use? And if all three are acceptable, in which use-cases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159feb8b-609c-327c-1247-e2f08dc8860a
* Version Independent ID: 4b990cb3-94d6-cfe9-d436-0d43d2e1b661
* Content: [endpoint - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/endpoint)
* Content Source: [styleguide/a-z-word-list-term-collections/e/endpoint.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/e/endpoint.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
hi,
I believe the information that you need is in the [user, end user](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/u/user-end-user) article.
