### ISSUE TITLE
What happened to the search box?

### ISSUE THREAD

**Issue by DonGlover** [MicrosoftDocs/microsoft-style-guide#9]
I am not seeing a search link. I thought I remembered there being one before the skin switch. Was I mistaken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/#feedback)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pallep** [comment]
Hi Don, 

Do you see the Search icon in the top right corner? This will perform a full-text search across all topics in the style guide. Let us know if this works...

**Comment by DonGlover** [comment]
I did not. I was getting a solid black background. I just cleared my cache and now I see the light colored menu bar above the guide. This with Chrome on Windows 10.
